from .controllers.organization_directory import organization_list
from .controllers.organization_workspace import organization_connections, organization_connection_result, organization_detach_preview, organization_connection_target
from .controllers.public_map_api import public_map
from .controllers.public_details import organization_detail as public_organization_detail, activity_detail
from .controllers.server_draft_api import draft_collection, draft_detail, draft_photo, draft_materialize
from .controllers.business_team_api import business_team_action, business_permission_config
from .controllers.workflow_notifications import inbox, mark_read, accept_invitation
from .controllers.location_resolution import location_resolve
from .controllers.typed_reviews import target_reviews, review_action
from .controllers.specialist_workspace import (specialist_workspace_index, specialist_workspace_profile,
    specialist_workspace_claims, specialist_workspace_invitations, specialist_workspace_certificates,
    specialist_workspace_review, organization_specialists, specialist_workspace_proposal,
    specialist_proposal_photo)
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, reverse_lazy

from .forms import UserPasswordResetForm, UserSetPasswordForm
from .phone_views import reveal_place_phones
from .photo_views import prepare_owner_photo, save_owner_photos, owner_photo_thumbnail
from .views import (
    home,
    events_landing,
    place_list,
    place_new,
    place_detail,
    place_detail_legacy,
    place_root_redirect,
    toggle_place_like,
    add_place_review,
    add_site_review,
    site_reviews,
    place_reviews,
    vote_place_review,
    vote_site_review,
    track_event,
    event_detail,
    seo_landing,
    about,
    faq_page,
    contacts,
    add_place,
    legacy_for_business_redirect,
    legacy_owner_section_redirect,
    legal_page,
    account_dashboard,
    account_favorites,
    account_profile,
    account_settings,
    account_deletion_request,
    account_deletion_confirm,
    account_deletion_cancel,
    account_deletion_status,
    account_register,
    account_verify_email,
    account_login,
    account_logout,
    UserPasswordResetView,
    owner_place_create,
    owner_place_delete,
    owner_place_draft,
    owner_place_edit,
    owner_place_gallery_photo_delete,
    owner_place_publish,
    owner_place_submit_review,
    owner_event_create,
    owner_event_manage, owner_event_cancel, owner_event_reschedule,
    owner_event_delete,
    owner_event_edit,
    owner_event_submit_review,
    owner_places_dashboard,
    owner_place_analytics,
    owner_review_approve,
    owner_review_reject,
    owner_reviews_dashboard,
    owner_team_accept_invitation,
    owner_team_cancel_invitation,
    owner_team_dashboard,
    owner_team_invite,
    owner_team_reject_invitation,
    owner_team_remove_member,
    owner_team_update_member_role,
    request_place_ownership,
    serve_specialist_document,
    specialist_list,
    specialist_detail,
    add_specialist_review,
    catalog_search_suggestions,
)

from catalog.controllers.organization_ownership_api import organization_ownership_action
from catalog.controllers.group_conditions import confirm_group_conditions
from catalog.controllers.program_workspace import program_create, program_detail, program_save
from catalog.controllers.organization_workspace import (organization_index, organization_create, organization_detail, organization_branch, organization_save, organization_join, organization_confirm, organization_detach, organization_branch_create, organization_join_recovery, organization_cancel)

urlpatterns = [
    path('account/specialists/', specialist_workspace_index, name='specialist_workspace_index'),
    path('account/specialists/<int:pk>/', specialist_workspace_profile, name='specialist_workspace_profile'),
    path('account/specialists/<int:pk>/claims/', specialist_workspace_claims, name='specialist_workspace_claims'),
    path('account/specialists/<int:pk>/invitations/', specialist_workspace_invitations, name='specialist_workspace_invitations'),
    path('account/specialists/<int:pk>/certificates/', specialist_workspace_certificates, name='specialist_workspace_certificates'),
    path('account/specialists/<int:pk>/review/', specialist_workspace_review, name='specialist_workspace_review'),
    path('account/organizations/<int:org_id>/specialists/', organization_specialists, name='organization_specialists'),
    path("organizations/", organization_list, name="organization_list"),
    path("organizations/<uuid:public_id>/", public_organization_detail, name="organization_detail"),
    path("activities/<int:pk>/", activity_detail, name="activity_detail"),
    path('account/notifications/', inbox, name='account_notifications'),
    path('account/notifications/<int:notification_id>/read/', mark_read, name='account_notification_read'),
    path('account/notifications/<int:notification_id>/accept/', accept_invitation, name='account_notification_accept'),
    path('account/organizations/', organization_index, name='organization_workspace_index'),
    path('account/organizations/create/', organization_create, name='organization_workspace_create'),
    path('account/organizations/connect/', organization_connection_target, name='organization_connection_target'),
    path('account/organization-operations/<uuid:operation_id>/', organization_connection_result, name='organization_connection_result'),
    path('account/organizations/<int:org_id>/connections/', organization_connections, name='organization_connections'),
    path('account/organizations/<int:org_id>/branches/<int:place_id>/detach-preview/', organization_detach_preview, name='organization_detach_preview'),
    path('account/organizations/<int:org_id>/', organization_detail, name='organization_workspace_detail'),
    path('account/organizations/<int:org_id>/programs/create/', program_create, name='organization_program_create'),
    path('account/organizations/<int:org_id>/programs/<int:program_id>/', program_detail, name='organization_program_detail'),
    path('account/organizations/<int:org_id>/programs/<int:program_id>/save/', program_save, name='organization_program_save'),
    path('account/organizations/<int:org_id>/branches/create/', organization_branch_create, name='organization_workspace_branch_create'),
    path('account/organizations/<int:org_id>/branches/<int:place_id>/', organization_branch, name='organization_workspace_branch'),
    path('account/organizations/<int:org_id>/save/', organization_save, name='organization_workspace_save'),
    path('account/organizations/<int:org_id>/join/', organization_join, name='organization_workspace_join'),
    path('account/organizations/<int:org_id>/requests/<int:request_id>/recovery/', organization_join_recovery, name='organization_join_recovery'),
    path('account/organizations/<int:org_id>/requests/<int:request_id>/cancel/', organization_cancel, name='organization_workspace_cancel'),
    path('account/organizations/<int:org_id>/requests/<int:request_id>/confirm/', organization_confirm, name='organization_workspace_confirm'),
    path('account/organizations/<int:org_id>/branches/<int:place_id>/detach/', organization_detach, name='organization_workspace_detach'),
    path('account/places/<int:place_id>/groups/<int:group_id>/confirm-conditions/', confirm_group_conditions, name='owner_group_confirm_conditions'),
    path("api/drafts/", draft_collection, name="server_draft_collection"),
    path("api/drafts/<uuid:draft_id>/", draft_detail, name="server_draft_detail"),
    path("api/drafts/<uuid:draft_id>/photo/", draft_photo, name="server_draft_photo"),
    path("api/drafts/<uuid:draft_id>/materialize/", draft_materialize, name="server_draft_materialize"),
    path("account/business/permissions/", business_permission_config, name="business_permission_config"),
    path("account/business/team/<str:target_type>/<int:target_id>/<str:action>/", business_team_action, name="business_team_action"),
    path('api/ownership/<str:action>/<str:target_type>/<int:target_id>/', organization_ownership_action, name='organization_ownership_action'),
    path("api/location/resolve/", location_resolve, name="location_resolve"),
    path("account/photos/prepare/", prepare_owner_photo, name="owner_photo_prepare"),
    path("account/places/<int:pk>/photo-thumbnail/<int:photo_id>/", owner_photo_thumbnail, name="owner_photo_thumbnail"),
    path("account/places/save-photos/", save_owner_photos, name="owner_photo_create_save"),
    path("account/places/<int:pk>/save-photos/", save_owner_photos, name="owner_photo_edit_save"),
    path("api/places/<int:pk>/phones/", reveal_place_phones, name="place_phone_reveal"),
    path("api/catalog/map/", public_map, name="public_map"),
    path("api/catalog/suggestions/", catalog_search_suggestions, name="catalog_search_suggestions"),
    path("", home, name="home"),
    path("events/", events_landing, name="events_landing"),
    path("catalog/", place_list, name="place_list"),
    path("catalog/new/", place_new, name="place_new"),
    path("catalog/<slug:seo_slug>/", seo_landing, name="seo_landing"),
    path("about/", about, name="about"),
    path("faq/", faq_page, name="faq_page"),
    path("contacts/", contacts, name="contacts"),
    path("reviews/", site_reviews, name="site_reviews"),
    path("place-reviews/", place_reviews, name="place_reviews"),
    path("add-place/", add_place, name="add_place"),
    path("for-business/", legacy_for_business_redirect, name="legacy_for_business"),
    path("privacy/", legal_page, {"page_slug": "privacy"}, name="privacy"),
    path("terms/", legal_page, {"page_slug": "terms"}, name="terms"),
    path("review-rules/", legal_page, {"page_slug": "review-rules"}, name="review_rules"),
    path("listing-rules/", legal_page, {"page_slug": "listing-rules"}, name="listing_rules"),
    path("account/", account_dashboard, name="account_dashboard"),
    path("account/profile/", account_profile, name="account_profile"),
    path("account/favorites/", account_favorites, name="account_favorites"),
    path("account/settings/", account_settings, name="account_settings"),
    path("account/deletion/", account_deletion_request, name="account_deletion_request"),
    path(
        "account/deletion/<uuid:subject_reference>/confirm/",
        account_deletion_confirm,
        name="account_deletion_confirm",
    ),
    path(
        "account/deletion/<uuid:subject_reference>/cancel/",
        account_deletion_cancel,
        name="account_deletion_cancel",
    ),
    path(
        "account/deletion/<uuid:subject_reference>/status/",
        account_deletion_status,
        name="account_deletion_status",
    ),
    path("auth/register/", account_register, name="account_register"),
    path("auth/verify-email/", account_verify_email, name="account_verify_email"),
    path("auth/login/", account_login, name="account_login"),
    path("auth/logout/", account_logout, name="account_logout"),
    path(
        "auth/password-reset/",
        UserPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "auth/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="auth/password_reset_confirm.html",
            form_class=UserSetPasswordForm,
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "auth/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("account/places/", owner_places_dashboard, name="owner_places_dashboard"),
    path("account/places/<int:pk>/analytics/", owner_place_analytics, name="owner_place_analytics"),
    path("account/places/create/", owner_place_create, name="owner_place_create"),
    path('account/places/events/<int:pk>/manage/', owner_event_manage, name='owner_event_manage'),
    path('account/places/events/<int:pk>/cancel/', owner_event_cancel, name='owner_event_cancel'),
    path('account/places/events/<int:pk>/reschedule/', owner_event_reschedule, name='owner_event_reschedule'),
    path("account/places/events/create/", owner_event_create, name="owner_event_create"),
    path('account/specialists/proposals/new/',specialist_workspace_proposal,name='specialist_workspace_proposal'),
    path('account/specialists/proposals/<uuid:draft_id>/',specialist_workspace_proposal,name='specialist_workspace_proposal_resume'),
    path('account/specialists/proposals/<uuid:draft_id>/photo/',specialist_proposal_photo,name='specialist_proposal_photo'),
    path("account/places/specialists/create/", specialist_workspace_profile, name="owner_specialist_create"),
    path("account/places/specialists/<int:pk>/edit/", specialist_workspace_profile, name="owner_specialist_edit"),
    path("account/places/events/<int:pk>/edit/", owner_event_edit, name="owner_event_edit"),
    path("account/places/events/<int:pk>/submit-review/", owner_event_submit_review, name="owner_event_submit_review"),
    path("account/places/events/<int:pk>/delete/", owner_event_delete, name="owner_event_delete"),
    path("account/places/<int:pk>/edit/", owner_place_edit, name="owner_place_edit"),
    path(
        "account/places/<int:pk>/photos/<int:photo_id>/delete/",
        owner_place_gallery_photo_delete,
        name="owner_place_gallery_photo_delete",
    ),
    path("account/places/<int:pk>/delete/", owner_place_delete, name="owner_place_delete"),
    path("account/places/<int:pk>/publish/", owner_place_publish, name="owner_place_publish"),
    path("account/places/<int:pk>/draft/", owner_place_draft, name="owner_place_draft"),
    path("account/places/<int:pk>/submit-review/", owner_place_submit_review, name="owner_place_submit_review"),
    path("account/places/team/", owner_team_dashboard, name="owner_team_dashboard"),
    path("account/places/team/invite/", owner_team_invite, name="owner_team_invite"),
    path("account/places/team/invitations/<int:invitation_id>/cancel/", owner_team_cancel_invitation, name="owner_team_cancel_invitation"),
    path("account/places/team/invitations/<int:invitation_id>/accept/", owner_team_accept_invitation, name="owner_team_accept_invitation"),
    path("account/places/team/invitations/<int:invitation_id>/reject/", owner_team_reject_invitation, name="owner_team_reject_invitation"),
    path("account/places/team/members/<int:membership_id>/role/", owner_team_update_member_role, name="owner_team_update_member_role"),
    path("account/places/team/members/<int:membership_id>/remove/", owner_team_remove_member, name="owner_team_remove_member"),
    path("account/places/reviews/", owner_reviews_dashboard, name="owner_reviews_dashboard"),
    path('reviews/<str:kind>/target/<int:pk>/', target_reviews, name='typed_reviews'),
    path('reviews/<str:kind>/<int:pk>/<str:action>/', review_action, name='typed_review_action'),
    path("account/places/reviews/<int:review_id>/approve/", owner_review_approve, name="owner_review_approve"),
    path("account/places/reviews/<int:review_id>/reject/", owner_review_reject, name="owner_review_reject"),
    re_path(
        r"^account/owner/(?P<subpath>.*)$",
        legacy_owner_section_redirect,
        name="legacy_owner_section",
    ),
    path("place/", place_root_redirect, name="place_root"),
    path("place/<int:pk>/", place_detail_legacy, name="place_detail_legacy"),
    path("place/<int:pk>-<str:slug>/", place_detail, name="place_detail"),
    path("place/<int:pk>/ownership-request/", request_place_ownership, name="request_place_ownership"),
    path("place/<int:pk>/like/", toggle_place_like, name="toggle_place_like"),
    path("place/<int:pk>/review/", add_place_review, name="add_place_review"),
    path("event/<int:pk>-<str:slug>/", event_detail, name="event_detail"),
    path("place-review/<int:review_id>/vote/", vote_place_review, name="vote_place_review"),
    path("review/", add_site_review, name="add_site_review"),
    path("site-review/<int:review_id>/vote/", vote_site_review, name="vote_site_review"),
    path("events/track/", track_event, name="track_event"),
    # Specialists
    path("specialists/", specialist_list, name="specialist_list"),
    path("specialists/<slug:slug>/", specialist_detail, name="specialist_detail"),
    path("specialists/<int:pk>/review/", add_specialist_review, name="add_specialist_review"),
    path("specialists/documents/<int:document_id>/download/", serve_specialist_document, name="serve_specialist_document"),
    # Old card links used a root-level ID and slug, before /place/ URLs.
    re_path(
        r"^(?P<pk>[0-9]+)-(?P<slug>[^/]+)/$",
        place_detail_legacy,
        name="place_detail_root_legacy",
    ),
]
