from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .forms import UserPasswordResetForm, UserSetPasswordForm
from .views import (
    home,
    events_landing,
    place_list,
    place_new,
    place_detail,
    place_detail_legacy,
    toggle_place_like,
    add_place_review,
    add_site_review,
    site_reviews,
    vote_place_review,
    vote_site_review,
    track_event,
    event_detail,
    seo_landing,
    about,
    contacts,
    for_business,
    legal_page,
    account_dashboard,
    account_favorites,
    account_profile,
    account_settings,
    account_register,
    account_verify_email,
    account_login,
    account_logout,
    owner_cabinet,
    owner_place_create,
    owner_place_delete,
    owner_place_draft,
    owner_place_edit,
    owner_place_publish,
    owner_place_submit_review,
    owner_event_create,
    owner_event_delete,
    owner_event_edit,
    owner_event_submit_review,
    owner_places_dashboard,
    owner_review_approve,
    owner_review_reject,
    owner_reviews_dashboard,
    owner_team_accept_invitation,
    owner_team_cancel_invitation,
    owner_team_dashboard,
    owner_team_invite,
    owner_team_reject_invitation,
    owner_team_remove_member,
    owner_team_update_member_role,
    request_place_ownership,
    serve_specialist_document,
    specialist_list,
    specialist_detail,
    add_specialist_review,
    owner_specialist_create,
    owner_specialist_edit,
)

urlpatterns = [
    path("", home, name="home"),
    path("events/", events_landing, name="events_landing"),
    path("catalog/", place_list, name="place_list"),
    path("catalog/new/", place_new, name="place_new"),
    path("catalog/<slug:seo_slug>/", seo_landing, name="seo_landing"),
    path("about/", about, name="about"),
    path("contacts/", contacts, name="contacts"),
    path("reviews/", site_reviews, name="site_reviews"),
    path("for-business/", for_business, name="for_business"),
    path("privacy/", legal_page, {"page_slug": "privacy"}, name="privacy"),
    path("terms/", legal_page, {"page_slug": "terms"}, name="terms"),
    path("review-rules/", legal_page, {"page_slug": "review-rules"}, name="review_rules"),
    path("listing-rules/", legal_page, {"page_slug": "listing-rules"}, name="listing_rules"),
    path("account/", account_dashboard, name="account_dashboard"),
    path("account/profile/", account_profile, name="account_profile"),
    path("account/favorites/", account_favorites, name="account_favorites"),
    path("account/settings/", account_settings, name="account_settings"),
    path("auth/register/", account_register, name="account_register"),
    path("auth/verify-email/", account_verify_email, name="account_verify_email"),
    path("auth/login/", account_login, name="account_login"),
    path("auth/logout/", account_logout, name="account_logout"),
    path(
        "auth/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="auth/password_reset_form.html",
            email_template_name="auth/password_reset_email.txt",
            subject_template_name="auth/password_reset_subject.txt",
            form_class=UserPasswordResetForm,
            success_url=reverse_lazy("password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "auth/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="auth/password_reset_confirm.html",
            form_class=UserSetPasswordForm,
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "auth/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("account/owner/", owner_cabinet, name="owner_cabinet"),
    path("account/owner/places/", owner_places_dashboard, name="owner_places_dashboard"),
    path("account/owner/places/create/", owner_place_create, name="owner_place_create"),
    path("account/owner/events/create/", owner_event_create, name="owner_event_create"),
    path("account/owner/specialists/create/", owner_specialist_create, name="owner_specialist_create"),
    path("account/owner/specialists/<int:pk>/edit/", owner_specialist_edit, name="owner_specialist_edit"),
    path("account/owner/events/<int:pk>/edit/", owner_event_edit, name="owner_event_edit"),
    path("account/owner/events/<int:pk>/submit-review/", owner_event_submit_review, name="owner_event_submit_review"),
    path("account/owner/events/<int:pk>/delete/", owner_event_delete, name="owner_event_delete"),
    path("account/owner/places/<int:pk>/edit/", owner_place_edit, name="owner_place_edit"),
    path("account/owner/places/<int:pk>/delete/", owner_place_delete, name="owner_place_delete"),
    path("account/owner/places/<int:pk>/publish/", owner_place_publish, name="owner_place_publish"),
    path("account/owner/places/<int:pk>/draft/", owner_place_draft, name="owner_place_draft"),
    path("account/owner/places/<int:pk>/submit-review/", owner_place_submit_review, name="owner_place_submit_review"),
    path("account/owner/team/", owner_team_dashboard, name="owner_team_dashboard"),
    path("account/owner/team/invite/", owner_team_invite, name="owner_team_invite"),
    path("account/owner/team/invitations/<int:invitation_id>/cancel/", owner_team_cancel_invitation, name="owner_team_cancel_invitation"),
    path("account/owner/team/invitations/<int:invitation_id>/accept/", owner_team_accept_invitation, name="owner_team_accept_invitation"),
    path("account/owner/team/invitations/<int:invitation_id>/reject/", owner_team_reject_invitation, name="owner_team_reject_invitation"),
    path("account/owner/team/members/<int:membership_id>/role/", owner_team_update_member_role, name="owner_team_update_member_role"),
    path("account/owner/team/members/<int:membership_id>/remove/", owner_team_remove_member, name="owner_team_remove_member"),
    path("account/owner/reviews/", owner_reviews_dashboard, name="owner_reviews_dashboard"),
    path("account/owner/reviews/<int:review_id>/approve/", owner_review_approve, name="owner_review_approve"),
    path("account/owner/reviews/<int:review_id>/reject/", owner_review_reject, name="owner_review_reject"),
    path("place/<int:pk>/", place_detail_legacy, name="place_detail_legacy"),
    path("place/<int:pk>-<str:slug>/", place_detail, name="place_detail"),
    path("place/<int:pk>/ownership-request/", request_place_ownership, name="request_place_ownership"),
    path("place/<int:pk>/like/", toggle_place_like, name="toggle_place_like"),
    path("place/<int:pk>/review/", add_place_review, name="add_place_review"),
    path("event/<int:pk>-<str:slug>/", event_detail, name="event_detail"),
    path("place-review/<int:review_id>/vote/", vote_place_review, name="vote_place_review"),
    path("review/", add_site_review, name="add_site_review"),
    path("site-review/<int:review_id>/vote/", vote_site_review, name="vote_site_review"),
    path("events/track/", track_event, name="track_event"),
    # Specialists
    path("specialists/", specialist_list, name="specialist_list"),
    path("specialists/<slug:slug>/", specialist_detail, name="specialist_detail"),
    path("specialists/<int:pk>/review/", add_specialist_review, name="add_specialist_review"),
    path("specialists/documents/<int:document_id>/download/", serve_specialist_document, name="serve_specialist_document"),
]
