# Generated by Django 6.0.2 on 2026-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('SPRT', 'Спорт'), ('ART', 'Творчество'), ('MUS', 'Музыка и сцена'), ('EDU', 'Образование'), ('TECH', 'Технологии'), ('FUN', 'Развлечения и досуг'), ('CAMP', 'Лагеря')], max_length=10, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, max_length=255, verbose_name='Подкатегория')),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('metro', models.CharField(blank=True, max_length=100, verbose_name='Метро')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('price_from', models.IntegerField(blank=True, null=True, verbose_name='Цена от')),
                ('price_to', models.IntegerField(blank=True, null=True, verbose_name='Цена до')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
