# Generated by Django 6.0.2 on 2026-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
