# Generated by Django 6.0.2 on 2026-02-24 07:15

import django.db.models.deletion
from django.db import migrations, models


def reset_place_likes(apps, schema_editor):
    Place = apps.get_model("catalog", "Place")
    Place.objects.all().update(likes_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_place_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-created_at',), 'verbose_name': 'Кружок/курс', 'verbose_name_plural': 'Кружки и курсы'},
        ),
        migrations.CreateModel(
            name='PlaceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_likes', to='catalog.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'constraints': [models.UniqueConstraint(fields=('place', 'session_key'), name='unique_place_like_per_session')],
            },
        ),
        migrations.RunPython(reset_place_likes, migrations.RunPython.noop),
    ]
