# Generated by Django 6.0.2 on 2026-02-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_sitesettings_empty_results_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating_avg',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='place',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80, verbose_name='Имя')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
            },
        ),
    ]
