# Generated by Django 6.0.2 on 2026-02-25 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_place_rating_avg_place_rating_count_placereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='placelike',
            name='unique_place_like_per_session',
        ),
        migrations.AddField(
            model_name='placelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='placelike',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия'),
        ),
        migrations.AddConstraint(
            model_name='placelike',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('place', 'session_key'), name='unique_place_like_per_session'),
        ),
        migrations.AddConstraint(
            model_name='placelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('place', 'user'), name='unique_place_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='placereview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('place', 'user'), name='unique_place_review_per_user'),
        ),
    ]
