# Generated by Django 6.0.2 on 2026-02-25 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_placereviewsbyclub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placereview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отзыв по кружку', 'verbose_name_plural': 'Отзывы по кружкам'},
        ),
        migrations.AlterModelOptions(
            name='placereviewsbyclub',
            options={'verbose_name': 'Рейтинг кружка', 'verbose_name_plural': 'Рейтинг кружков'},
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80, verbose_name='Имя')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_site_review_per_user')],
            },
        ),
    ]
