# Generated by Django 6.0.2 on 2026-02-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_placereview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
    ]
