# Generated by Django 6.0.2 on 2026-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='Временное мероприятие'),
        ),
        migrations.AddField(
            model_name='place',
            name='temporary_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание мероприятия'),
        ),
        migrations.AddField(
            model_name='place',
            name='temporary_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало мероприятия'),
        ),
    ]
