# Generated by Django 6.0.2 on 2026-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_place_is_temporary_place_temporary_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_text_az',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Hero кнопка (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_text_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Hero кнопка (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_text_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Hero кнопка (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_show_decor',
            field=models.BooleanField(default=True, verbose_name='Показывать декор в hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_label_az',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero подпись поиска (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_label_en',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero подпись поиска (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_label_ru',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero подпись поиска (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_placeholder_az',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero placeholder поиска (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_placeholder_en',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero placeholder поиска (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_search_placeholder_ru',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero placeholder поиска (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_subtitle_az',
            field=models.CharField(blank=True, default='', max_length=260, verbose_name='Hero подзаголовок (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_subtitle_en',
            field=models.CharField(blank=True, default='', max_length=260, verbose_name='Hero подзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_subtitle_ru',
            field=models.CharField(blank=True, default='', max_length=260, verbose_name='Hero подзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_az',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero заголовок (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_en',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title_ru',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Hero заголовок (RU)'),
        ),
    ]
