# Generated by Django 6.0.2 on 2026-02-27 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_sitesettings_home_cta_text_az_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('catalog_search', 'Поиск в каталоге'), ('catalog_filter', 'Применение фильтров'), ('place_open', 'Открытие карточки'), ('cta_call', 'Клик: Позвонить'), ('cta_whatsapp', 'Клик: WhatsApp'), ('cta_instagram', 'Клик: Instagram')], db_index=True, max_length=32, verbose_name='Событие')),
                ('day', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='День')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='Путь')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия')),
                ('event_meta', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='catalog.place', verbose_name='Кружок/курс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие воронки',
                'verbose_name_plural': 'События воронки',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['day', 'event_type'], name='catalog_fun_day_cec371_idx'), models.Index(fields=['event_type', 'created_at'], name='catalog_fun_event_t_5cb88a_idx')],
            },
        ),
    ]
