# Generated by Django 6.0.2 on 2026-03-10 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_places', to=settings.AUTH_USER_MODEL, verbose_name='Владелец карточки'),
        ),
        migrations.CreateModel(
            name='PlaceOwnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], db_index=True, default='PENDING', max_length=16, verbose_name='Статус')),
                ('note', models.TextField(blank=True, default='', verbose_name='Комментарий заявителя')),
                ('moderation_note', models.TextField(blank=True, default='', verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ownership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to='catalog.place', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Заявка на владение кружком',
                'verbose_name_plural': 'Заявки на владение кружком',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlaceOwnershipRequestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Создана'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], max_length=16, verbose_name='Событие')),
                ('from_status', models.CharField(blank=True, default='', max_length=16, verbose_name='Статус до')),
                ('to_status', models.CharField(blank=True, default='', max_length=16, verbose_name='Статус после')),
                ('note', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_request_audits', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('ownership_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='catalog.placeownershiprequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Аудит заявки на владение',
                'verbose_name_plural': 'Аудит заявок на владение',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='placeownershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('place', 'applicant'), name='unique_pending_ownership_request_per_user_place'),
        ),
    ]
