# Generated by Django 6.0.2 on 2026-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_place_owner_placeownershiprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner_permissions_override',
            field=models.JSONField(blank=True, default=list, help_text='Оставьте пустым, чтобы использовать права по умолчанию для роли владельца.', verbose_name='Переопределение прав владельца'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner_role',
            field=models.CharField(choices=[('MANAGER', 'Owner manager'), ('MODERATOR', 'Owner moderator'), ('EDITOR', 'Owner editor')], default='MANAGER', help_text='Используется только для пользователей со статусом владельца.', max_length=16, verbose_name='Роль владельца'),
        ),
    ]
