# Generated by Django 6.0.2 on 2026-03-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_userprofile_owner_permissions_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceChangeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=64, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Новое значение')),
                ('source', models.CharField(choices=[('OWNER_PANEL', 'Кабинет владельца'), ('ADMIN', 'Админка'), ('SYSTEM', 'Система')], db_index=True, default='OWNER_PANEL', max_length=24, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_change_audits', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_audits', to='catalog.place', verbose_name='Кружок')),
            ],
            options={
                'verbose_name': 'Аудит изменения карточки',
                'verbose_name_plural': 'Аудит изменений карточек',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OwnerTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email приглашенного')),
                ('role', models.CharField(choices=[('MANAGER', 'Owner manager'), ('MODERATOR', 'Owner moderator'), ('EDITOR', 'Owner editor')], db_index=True, default='EDITOR', max_length=16, verbose_name='Роль в команде')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает ответа'), ('ACCEPTED', 'Принято'), ('REJECTED', 'Отклонено'), ('CANCELED', 'Отменено')], db_index=True, default='PENDING', max_length=16, verbose_name='Статус')),
                ('token', models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='Токен приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_team_sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_team_received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный пользователь')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец команды')),
            ],
            options={
                'verbose_name': 'Приглашение в команду владельца',
                'verbose_name_plural': 'Приглашения в команду владельца',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('owner', 'email'), name='unique_pending_team_invitation_per_owner_email'), models.CheckConstraint(condition=models.Q(('owner', models.F('invited_user')), _negated=True), name='owner_invited_user_not_owner')],
            },
        ),
        migrations.CreateModel(
            name='OwnerTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Owner manager'), ('MODERATOR', 'Owner moderator'), ('EDITOR', 'Owner editor')], db_index=True, default='EDITOR', max_length=16, verbose_name='Роль в команде')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_team_sent_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_team_members', to=settings.AUTH_USER_MODEL, verbose_name='Владелец команды')),
            ],
            options={
                'verbose_name': 'Участник команды владельца',
                'verbose_name_plural': 'Участники команды владельца',
                'ordering': ('owner_id', 'member_id'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'member'), name='unique_owner_team_member'), models.CheckConstraint(condition=models.Q(('owner', models.F('member')), _negated=True), name='owner_team_member_not_owner')],
            },
        ),
    ]
