# Generated by Django 6.0.2 on 2026-03-11 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email для подтверждения')),
                ('code_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Код действует до')),
                ('resend_available_at', models.DateTimeField(blank=True, null=True, verbose_name='Повторная отправка после')),
                ('attempts_left', models.PositiveSmallIntegerField(default=5, verbose_name='Осталось попыток')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Email подтвержден')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подтверждение email',
                'verbose_name_plural': 'Подтверждение email',
                'ordering': ('-updated_at',),
            },
        ),
    ]
