# Generated by Django 6.0.2 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_useremailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("U", "Не указан"), ("M", "Мужской"), ("F", "Женский")],
                db_index=True,
                default="U",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
    ]
