# Generated by Django 6.0.2 on 2026-03-12 12:35

from django.db import migrations


def update_public_contacts_defaults(apps, schema_editor):
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    obj = SiteSettings.objects.order_by("id").first()
    if not obj:
        return

    changed_fields = []

    if (obj.footer_email or "").strip().lower() in {"", "kidsmap@example.com"}:
        obj.footer_email = "kidsmap.az@gmail.com"
        changed_fields.append("footer_email")

    instagram_value = (obj.footer_instagram or "").strip().rstrip("/")
    if instagram_value in {
        "",
        "kidsmap",
        "@kidsmap",
        "instagram.com/kidsmap",
        "www.instagram.com/kidsmap",
        "https://instagram.com/kidsmap",
        "https://www.instagram.com/kidsmap",
    }:
        obj.footer_instagram = "https://www.instagram.com/kidsmap.az/"
        changed_fields.append("footer_instagram")

    for field_name in ("contacts_text_ru", "contacts_text_en", "contacts_text_az"):
        value = getattr(obj, field_name) or ""
        if "kidsmap@example.com" in value:
            setattr(obj, field_name, value.replace("kidsmap@example.com", "kidsmap.az@gmail.com"))
            changed_fields.append(field_name)

    if changed_fields:
        obj.save(update_fields=[*sorted(set(changed_fields)), "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_userprofile_gender"),
    ]

    operations = [
        migrations.RunPython(update_public_contacts_defaults, migrations.RunPython.noop),
    ]

