# Generated by Django 6.0.2 on 2026-03-13 07:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0030_update_public_contacts_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRegisteredUser',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь сайта',
                'verbose_name_plural': 'Пользователи сайта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccessUser',
            fields=[
            ],
            options={
                'verbose_name': 'Сотрудник админки',
                'verbose_name_plural': 'Сотрудники админки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
