# Generated by Django 6.0.2 on 2026-03-31 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_siteregistereduser_staffaccessuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='place',
            name='extra_conditions',
            field=models.TextField(blank=True, verbose_name='Дополнительные условия'),
        ),
        migrations.AddField(
            model_name='place',
            name='lesson_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность урока (мин)'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_per_8_lessons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за 8 уроков'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_per_lesson',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за 1 урок'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_per_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за месяц'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='contains_profanity',
            field=models.BooleanField(default=False, verbose_name='Содержит скрытую лексику'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='contains_profanity',
            field=models.BooleanField(default=False, verbose_name='Содержит скрытую лексику'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.CreateModel(
            name='PlaceReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.placereview', verbose_name='Отзыв')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_review_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на отзыв по кружку',
                'verbose_name_plural': 'Реакции на отзывы по кружкам',
                'constraints': [models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('review', 'session_key'), name='unique_place_review_reaction_per_session'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='unique_place_review_reaction_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SiteReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Сессия')),
                ('value', models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], default=1, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.sitereview', verbose_name='Отзыв о сайте')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_review_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на отзыв о сайте',
                'verbose_name_plural': 'Реакции на отзывы о сайте',
                'constraints': [models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('review', 'session_key'), name='unique_site_review_reaction_per_session'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='unique_site_review_reaction_per_user')],
            },
        ),
    ]
