# Generated by Codex on 2026-03-31

from django.db import migrations


DEFAULT_PHONE = "+994 50 540 66 39"


def update_footer_phone_default(apps, schema_editor):
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    obj = SiteSettings.objects.order_by("id").first()
    if not obj:
        return

    current_phone = (obj.footer_phone or "").strip()
    if current_phone == DEFAULT_PHONE:
        return

    obj.footer_phone = DEFAULT_PHONE
    obj.save(update_fields=["footer_phone", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_place_additional_info_place_extra_conditions_and_more"),
    ]

    operations = [
        migrations.RunPython(update_footer_phone_default, migrations.RunPython.noop),
    ]
