# Generated by Codex on 2026-03-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_update_footer_phone_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="place",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалил",
            ),
        ),
    ]
