# Generated by Codex on 2026-03-31

from django.db import migrations, models


DEFAULT_SOCIAL_LINKS = {
    "footer_telegram": "https://t.me/KidsMap_az",
    "footer_youtube": "https://www.youtube.com/@KidsMap_az",
    "footer_tiktok": "https://www.tiktok.com/@kidsmap.az?lang=ru-RU",
    "footer_facebook": "https://www.facebook.com/people/KidsMap/61583913364027/",
    "footer_linkedin": "https://www.linkedin.com/company/kidsmap-az/",
}


def populate_site_social_links(apps, schema_editor):
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    obj = SiteSettings.objects.order_by("id").first()
    if not obj:
        return

    changed_fields = []
    for field_name, default_value in DEFAULT_SOCIAL_LINKS.items():
        if (getattr(obj, field_name) or "").strip():
            continue
        setattr(obj, field_name, default_value)
        changed_fields.append(field_name)

    if changed_fields:
        obj.save(update_fields=[*changed_fields, "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_place_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_facebook",
            field=models.URLField(blank=True, default="", verbose_name="Facebook в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_linkedin",
            field=models.URLField(blank=True, default="", verbose_name="LinkedIn в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_telegram",
            field=models.URLField(blank=True, default="", verbose_name="Telegram в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_tiktok",
            field=models.URLField(blank=True, default="", verbose_name="TikTok в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_youtube",
            field=models.URLField(blank=True, default="", verbose_name="YouTube в футере"),
        ),
        migrations.RunPython(populate_site_social_links, migrations.RunPython.noop),
    ]
