# Generated by Django 6.0.2 on 2026-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_sitesettings_add_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('HOME_HERO', 'Главная: hero-слайдер'), ('HOME_PARTNERS', 'Главная: партнёры')], db_index=True, default='HOME_HERO', max_length=32, verbose_name='Где показывать')),
                ('image', models.FileField(help_text='Загрузите JPG/WebP/PNG. Для hero лучше 1200x900 или 900x1200, до 2 MB.', upload_to='site/gallery/', verbose_name='Изображение')),
                ('category', models.CharField(blank=True, choices=[('SPRT', 'Спорт'), ('ART', 'Творчество'), ('MUS', 'Музыка и сцена'), ('EDU', 'Образование'), ('TECH', 'Технологии'), ('FUN', 'Развлечения и досуг'), ('CAMP', 'Лагеря')], default='', help_text='Нужно для подписи фото в hero или будущих подборок.', max_length=10, verbose_name='Категория')),
                ('title_ru', models.CharField(blank=True, default='', max_length=120, verbose_name='Подпись (RU)')),
                ('title_en', models.CharField(blank=True, default='', max_length=120, verbose_name='Подпись (EN)')),
                ('title_az', models.CharField(blank=True, default='', max_length=120, verbose_name='Подпись (AZ)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Фото для блоков сайта',
                'verbose_name_plural': 'Фото для блоков сайта',
                'ordering': ('placement', 'order', 'id'),
            },
        ),
    ]
