# Generated by Django 6.0.2 on 2026-05-18 10:45

from django.db import migrations, models


def migrate_existing_moderation_state(apps, schema_editor):
    Place = apps.get_model('catalog', 'Place')
    PlaceReview = apps.get_model('catalog', 'PlaceReview')
    SiteReview = apps.get_model('catalog', 'SiteReview')

    for place in Place.objects.all().only('id', 'is_active', 'deleted_at', 'created_at', 'status', 'published_at'):
        if place.deleted_at is not None:
            place.status = 'rejected'
        elif place.is_active:
            place.status = 'published'
            if place.published_at is None:
                place.published_at = place.created_at
        else:
            place.status = 'draft'
        place.save(update_fields=['status', 'published_at'])

    PlaceReview.objects.filter(is_approved=True).update(status='approved')
    PlaceReview.objects.filter(is_approved=False).update(status='pending')
    SiteReview.objects.filter(is_approved=True).update(status='approved')
    SiteReview.objects.filter(is_approved=False).update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_expand_catalog_to_azerbaijan'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Информация проверена'),
        ),
        migrations.AddField(
            model_name='place',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='place',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='published', max_length=16, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='approved', max_length=16, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='approved', max_length=16, verbose_name='Статус модерации'),
        ),
        migrations.RunPython(migrate_existing_moderation_state, migrations.RunPython.noop),
    ]
