# Generated by Django 6.0.2 on 2026-05-22 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_quarantine_low_quality_public_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='Slug')),
                ('name_az', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (AZ)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('description_az', models.TextField(blank=True, default='', verbose_name='Описание (AZ)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('category', models.CharField(choices=[('SPRT', 'Спорт'), ('ART', 'Творчество'), ('MUS', 'Музыка и сцена'), ('EDU', 'Образование'), ('TECH', 'Технологии'), ('FUN', 'Развлечения и досуг'), ('CAMP', 'Лагеря')], max_length=10, verbose_name='Категория')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начало мероприятия')),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Окончание мероприятия')),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('price_text', models.CharField(blank=True, default='', max_length=120, verbose_name='Цена')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон / WhatsApp')),
                ('instagram', models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram')),
                ('photo', models.FileField(blank=True, null=True, upload_to='events/', verbose_name='Основное фото')),
                ('moderation_note', models.TextField(blank=True, default='', verbose_name='Комментарий для модерации')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('expired', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=16, verbose_name='Статус модерации')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец мероприятия')),
                ('related_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.place', verbose_name='Связанное место')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('start_datetime', '-created_at'),
                'indexes': [models.Index(fields=['status', 'start_datetime'], name='catalog_eve_status_f6417a_idx'), models.Index(fields=['owner', 'status'], name='catalog_eve_owner_i_93d137_idx'), models.Index(fields=['end_datetime'], name='catalog_eve_end_dat_262afc_idx')],
            },
        ),
    ]
