# Generated by Django 6.0.2 on 2026-06-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-created_at',), 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='placereviewsbyclub',
            options={'verbose_name': 'Рейтинг места', 'verbose_name_plural': 'Рейтинги мест'},
        ),
    ]
