# Generated by Django 6.0.2 on 2026-06-23 11:20

import django.db.models.deletion
from django.db import migrations, models


def populate_categories(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    # Use hardcoded Russian translation as the default for the name and name_ru
    choices = [
        ("SPRT", "Спорт"),
        ("ART", "Творчество"),
        ("MUS", "Музыка и сцена"),
        ("EDU", "Образование"),
        ("TECH", "Технологии"),
        ("FUN", "Развлечения и досуг"),
        ("CAMP", "Лагеря"),
    ]
    for order, (code, name) in enumerate(choices, start=1):
        Category.objects.get_or_create(
            code=code,
            defaults={"name": name, "name_ru": name, "order": order}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_alter_place_options_alter_placereviewsbyclub_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_az', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (AZ)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('icon', models.CharField(blank=True, default='', help_text='Класс иконки или название', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RunPython(populate_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_az', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (AZ)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('category', 'order', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.RunSQL("UPDATE catalog_place SET subcategory_id = NULL WHERE subcategory_id = '';", migrations.RunSQL.noop),
    ]
