# Generated by Django 6.0.2 on 2026-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_category_is_active_subcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name_ru',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category', 'name_ru'), 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
