# Generated by Django 6.0.2 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется на странице О проекте.', null=True, upload_to='site/', verbose_name="Баннер страницы 'О проекте'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется в каталоге.', null=True, upload_to='site/', verbose_name='Баннер каталога'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется в личном кабинете.', null=True, upload_to='site/', verbose_name='Баннер личного кабинета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='for_business_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется на странице владельцев.', null=True, upload_to='site/', verbose_name='Баннер страницы владельцам'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется на странице отзывов.', null=True, upload_to='site/', verbose_name='Баннер страницы отзывов'),
        ),
    ]
