# Generated by Django 6.0.2 on 2026-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_sitesettings_about_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Класс иконки или название', max_length=255, verbose_name='Иконка'),
        ),
    ]
