# Generated by Codex on 2026-06-30

from django.db import migrations, models


def populate_compatibility_fields(apps, schema_editor):
    PlaceLike = apps.get_model("catalog", "PlaceLike")
    PlaceReviewReaction = apps.get_model("catalog", "PlaceReviewReaction")
    SiteReviewReaction = apps.get_model("catalog", "SiteReviewReaction")
    PlaceOwnershipRequest = apps.get_model("catalog", "PlaceOwnershipRequest")
    OwnerTeamInvitation = apps.get_model("catalog", "OwnerTeamInvitation")

    for like in PlaceLike.objects.all().iterator():
        normalized = (like.session_key or "").strip() or None
        PlaceLike.objects.filter(pk=like.pk).update(session_key_unique=normalized)

    for reaction in PlaceReviewReaction.objects.all().iterator():
        normalized = (reaction.session_key or "").strip() or None
        PlaceReviewReaction.objects.filter(pk=reaction.pk).update(session_key_unique=normalized)

    for reaction in SiteReviewReaction.objects.all().iterator():
        normalized = (reaction.session_key or "").strip() or None
        SiteReviewReaction.objects.filter(pk=reaction.pk).update(session_key_unique=normalized)

    for request in PlaceOwnershipRequest.objects.all().iterator():
        marker = "PENDING" if request.status == "PENDING" else None
        PlaceOwnershipRequest.objects.filter(pk=request.pk).update(pending_constraint_key=marker)

    for invitation in OwnerTeamInvitation.objects.all().iterator():
        normalized_email = (invitation.email or "").strip().lower()
        pending_email = normalized_email if invitation.status == "PENDING" else None
        OwnerTeamInvitation.objects.filter(pk=invitation.pk).update(
            email=normalized_email,
            pending_email=pending_email,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerteaminvitation",
            name="pending_email",
            field=models.EmailField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="placeownershiprequest",
            name="pending_constraint_key",
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="placelike",
            name="session_key_unique",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="placereviewreaction",
            name="session_key_unique",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="sitereviewreaction",
            name="session_key_unique",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(populate_compatibility_fields, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="ownerteaminvitation",
            name="unique_pending_team_invitation_per_owner_email",
        ),
        migrations.RemoveConstraint(
            model_name="placeownershiprequest",
            name="unique_pending_ownership_request_per_user_place",
        ),
        migrations.RemoveConstraint(
            model_name="placelike",
            name="unique_place_like_per_session",
        ),
        migrations.RemoveConstraint(
            model_name="placelike",
            name="unique_place_like_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="placereview",
            name="unique_place_review_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="placereviewreaction",
            name="unique_place_review_reaction_per_session",
        ),
        migrations.RemoveConstraint(
            model_name="placereviewreaction",
            name="unique_place_review_reaction_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="sitereview",
            name="unique_site_review_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="sitereviewreaction",
            name="unique_site_review_reaction_per_session",
        ),
        migrations.RemoveConstraint(
            model_name="sitereviewreaction",
            name="unique_site_review_reaction_per_user",
        ),
        migrations.AddConstraint(
            model_name="ownerteaminvitation",
            constraint=models.UniqueConstraint(fields=("owner", "pending_email"), name="unique_pending_team_invitation_per_owner_email"),
        ),
        migrations.AddConstraint(
            model_name="placeownershiprequest",
            constraint=models.UniqueConstraint(fields=("place", "applicant", "pending_constraint_key"), name="unique_pending_ownership_request_per_user_place"),
        ),
        migrations.AddConstraint(
            model_name="placelike",
            constraint=models.UniqueConstraint(fields=("place", "session_key_unique"), name="unique_place_like_per_session"),
        ),
        migrations.AddConstraint(
            model_name="placelike",
            constraint=models.UniqueConstraint(fields=("place", "user"), name="unique_place_like_per_user"),
        ),
        migrations.AddConstraint(
            model_name="placereview",
            constraint=models.UniqueConstraint(fields=("place", "user"), name="unique_place_review_per_user"),
        ),
        migrations.AddConstraint(
            model_name="placereviewreaction",
            constraint=models.UniqueConstraint(fields=("review", "session_key_unique"), name="unique_place_review_reaction_per_session"),
        ),
        migrations.AddConstraint(
            model_name="placereviewreaction",
            constraint=models.UniqueConstraint(fields=("review", "user"), name="unique_place_review_reaction_per_user"),
        ),
        migrations.AddConstraint(
            model_name="sitereview",
            constraint=models.UniqueConstraint(fields=("user",), name="unique_site_review_per_user"),
        ),
        migrations.AddConstraint(
            model_name="sitereviewreaction",
            constraint=models.UniqueConstraint(fields=("review", "session_key_unique"), name="unique_site_review_reaction_per_session"),
        ),
        migrations.AddConstraint(
            model_name="sitereviewreaction",
            constraint=models.UniqueConstraint(fields=("review", "user"), name="unique_site_review_reaction_per_user"),
        ),
    ]
