# Generated by Django 6.0.2 on 2026-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_placescheduleday_placescheduleinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_bg',
            field=models.CharField(blank=True, default='#F3F4F6', help_text='Например: #E8F5EE', max_length=20, verbose_name='Цвет фона (HEX)'),
        ),
        migrations.AddField(
            model_name='category',
            name='color_text',
            field=models.CharField(blank=True, default='#6B7280', help_text='Например: #0C7A47', max_length=20, verbose_name='Цвет иконки (HEX)'),
        ),
    ]
