# Generated by Codex on 2026-07-08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_category_color_bg_category_color_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Загрузите JPG, PNG или WebP. Используется в админке и профиле пользователя.",
                upload_to="user_avatars/",
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "webp"])],
                verbose_name="Фото профиля",
            ),
        ),
    ]
