# Generated by Django 6.0.2 on 2026-07-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_az', models.CharField(max_length=255, verbose_name='Название (AZ)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'ordering': ('name_ru',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_az', models.CharField(max_length=255, verbose_name='Название (AZ)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name_ru',),
            },
        ),
        migrations.CreateModel(
            name='SpecialistSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название (системное)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_az', models.CharField(max_length=255, verbose_name='Название (AZ)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ('order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_az', models.CharField(max_length=255, verbose_name='Название (AZ)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='catalog.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ('name_ru',),
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия')),
                ('name_alt', models.CharField(blank=True, default='', help_text='Например, латиница/кириллица для поиска', max_length=255, verbose_name='Альтернативное имя / Транслитерация')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.FileField(blank=True, null=True, upload_to='specialists/photos/', verbose_name='Фото профиля')),
                ('bio_ru', models.TextField(blank=True, default='', verbose_name='О себе (RU)')),
                ('bio_az', models.TextField(blank=True, default='', verbose_name='О себе (AZ)')),
                ('bio_en', models.TextField(blank=True, default='', verbose_name='О себе (EN)')),
                ('consultation_format', models.CharField(choices=[('online', 'Только онлайн'), ('offline', 'Только очно'), ('both', 'Онлайн и очно')], default='both', max_length=10, verbose_name='Формат работы')),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж (лет)')),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('rating_avg', models.FloatField(default=0, editable=False, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликован'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16, verbose_name='Статус модерации')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_specialists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец профиля')),
                ('specializations', models.ManyToManyField(related_name='specialists', to='catalog.specialistspecialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecialistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', 'Удостоверение личности (приватно)'), ('diploma', 'Диплом'), ('certificate', 'Сертификат')], max_length=20, verbose_name='Тип документа')),
                ('name', models.CharField(max_length=255, verbose_name='Название / Описание документа')),
                ('file', models.FileField(upload_to='protected_docs/specialists/', verbose_name='Файл документа')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Проверен'), ('rejected', 'Отклонен')], default='pending', max_length=16, verbose_name='Статус проверки')),
                ('is_published', models.BooleanField(default=False, help_text='Разрешить публичный показ диплома/сертификата после прохождения проверки', verbose_name='Показывать в профиле')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Документ специалиста',
                'verbose_name_plural': 'Документы специалиста',
            },
        ),
        migrations.CreateModel(
            name='SpecialistPracticeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Собственный адрес/кабинет')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('schedule', models.TextField(blank=True, verbose_name='Расписание (текст)')),
                ('price_per_session', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость приема (AZN)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон для записи в филиале')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.district', verbose_name='Район')),
                ('metro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.metrostation', verbose_name='Метро')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.place', verbose_name='Детский центр (KidsMap)')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.region', verbose_name='Город / Регион')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_locations', to='catalog.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Локация практики',
                'verbose_name_plural': 'Локации практики',
            },
        ),
        migrations.CreateModel(
            name='SpecialistScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('is_closed', models.BooleanField(default=True, verbose_name='Закрыто')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24 часа')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('practice_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='catalog.specialistpracticelocation', verbose_name='Локация практики')),
            ],
            options={
                'verbose_name': 'День расписания специалиста',
                'verbose_name_plural': 'Дни расписания специалиста',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SpecialistScheduleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='catalog.specialistscheduleday', verbose_name='День расписания')),
            ],
            options={
                'verbose_name': 'Интервал расписания специалиста',
                'verbose_name_plural': 'Интервалы расписания специалиста',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SpecialistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=16, verbose_name='Статус модерации')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.specialist', verbose_name='Специалист')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о специалисте',
                'verbose_name_plural': 'Отзывы о специалистах',
                'constraints': [models.UniqueConstraint(fields=('specialist', 'user'), name='unique_specialist_review_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='specialistscheduleday',
            constraint=models.UniqueConstraint(fields=('practice_location', 'weekday'), name='unique_spec_schedule_weekday'),
        ),
    ]
