# Generated by Django 6.0.2 on 2026-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_seed_specialist_locations_and_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Продолжительность приема (минут)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='education_az',
            field=models.TextField(blank=True, default='', verbose_name='Образование (AZ)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='education_en',
            field=models.TextField(blank=True, default='', verbose_name='Образование (EN)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='education_ru',
            field=models.TextField(blank=True, default='', verbose_name='Образование (RU)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_info_az',
            field=models.TextField(blank=True, default='', verbose_name='Опыт работы (AZ)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_info_en',
            field=models.TextField(blank=True, default='', verbose_name='Опыт работы (EN)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_info_ru',
            field=models.TextField(blank=True, default='', verbose_name='Опыт работы (RU)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='language_az',
            field=models.BooleanField(default=False, verbose_name='Азербайджанский'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='language_en',
            field=models.BooleanField(default=False, verbose_name='Английский'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='language_ru',
            field=models.BooleanField(default=False, verbose_name='Русский'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость от (AZN)'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='price_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость до (AZN)'),
        ),
    ]
