# Generated by Django 6.0.2 on 2026-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_specialist_duration_minutes_specialist_education_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='WhatsApp'),
        ),
    ]
