# Generated by Django 6.0.2 on 2026-07-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_specialist_phone_specialist_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-created_at',), 'verbose_name': 'Постоянное место', 'verbose_name_plural': 'Постоянные места'},
        ),
    ]
