# Generated by Django 6.0.2 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0059_seed_educator_specializations"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="specialists_section_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Скрывает публичный каталог, ссылки в навигации и owner-формы. Данные и админка специалистов сохраняются.",
                verbose_name="Показывать раздел «Педагоги и специалисты»",
            ),
        ),
    ]
