# Generated by Django 6.0.2 on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0060_sitesettings_specialists_section_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisibilitySettings",
            fields=[],
            options={
                "verbose_name": "Разделы сайта",
                "verbose_name_plural": "Разделы сайта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.sitesettings",),
        ),
    ]
