# Generated by Django 6.0.2 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0067_place_offers_adult_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="phone2",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Дополнительный телефон"),
        ),
        migrations.AddField(
            model_name="place",
            name="phone3",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Ещё один телефон"),
        ),
    ]
