# Generated by Django 6.0.2 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("catalog", "0068_place_phone2_place_phone3")]

    operations = [
        migrations.AddField(model_name="place", name="extra_conditions_az", field=models.TextField(blank=True, default="", verbose_name="Дополнительные условия (AZ)")),
        migrations.AddField(model_name="place", name="extra_conditions_ru", field=models.TextField(blank=True, default="", verbose_name="Дополнительные условия (RU)")),
        migrations.AddField(model_name="place", name="extra_conditions_en", field=models.TextField(blank=True, default="", verbose_name="Дополнительные условия (EN)")),
        migrations.AddField(model_name="place", name="additional_info_az", field=models.TextField(blank=True, default="", verbose_name="Дополнительная информация (AZ)")),
        migrations.AddField(model_name="place", name="additional_info_ru", field=models.TextField(blank=True, default="", verbose_name="Дополнительная информация (RU)")),
        migrations.AddField(model_name="place", name="additional_info_en", field=models.TextField(blank=True, default="", verbose_name="Дополнительная информация (EN)")),
    ]
