# Generated by Django 6.0.2 on 2026-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_alter_sitegalleryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegalleryimage',
            name='category',
            field=models.CharField(blank=True, choices=[('SPRT', 'Спорт'), ('water-leisure', 'Водный отдых'), ('parks-playgrounds', 'Парки и детские площадки'), ('FUN', 'Развлечения и досуг'), ('ZOO', 'Зоопарки'), ('museums-culture', 'Музеи и культура'), ('dance', 'Танцы'), ('EDU', 'Образование'), ('early-development', 'Дошкольное развитие'), ('ART', 'Творчество'), ('theater-stage', 'Театр и сцена'), ('MUS', 'Музыка'), ('intellect-skills', 'Интеллект и навыки'), ('TECH', 'Наука и технологии'), ('development-support', 'Развитие и поддержка'), ('CAMP', 'Лагеря'), ('excursions-tours', 'Экскурсии и туры')], default='', help_text='Нужно для подписи фото в hero или будущих подборок.', max_length=50, verbose_name='Категория'),
        ),
    ]
