# Generated by Django 6.0.2 on 2026-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_pricingplan_relational'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price__gt', 0), ('price_kind', 'exact'), ('price_max__isnull', True), ('price_min__isnull', True)), models.Q(('price', 0), ('price_kind', 'free'), ('price_max__isnull', True), ('price_min__isnull', True)), models.Q(('price__isnull', True), ('price_kind', 'from'), ('price_max__isnull', True), ('price_min__gt', 0)), models.Q(('price__isnull', True), ('price_kind', 'range'), ('price_max__isnull', False), ('price_min__isnull', False)), models.Q(('price__isnull', True), ('price_kind', 'on_request'), ('price_max__isnull', True), ('price_min__isnull', True)), _connector='OR'), name='pricing_kind_values'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_cycles__isnull', True), ('billing_interval', ''), ('billing_interval_count__isnull', True), ('billing_mode', 'one_time')), models.Q(('billing_cycles__isnull', True), ('billing_interval__in', ('day', 'week', 'month', 'year')), ('billing_interval_count__gt', 0), ('billing_mode', 'recurring')), models.Q(('billing_cycles__gt', 0), ('billing_interval', ''), ('billing_interval_count__isnull', True), ('billing_mode', 'installment')), _connector='OR'), name='pricing_billing_values'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__isnull', True), ('quantity_unit', '')), models.Q(('quantity__gt', 0), models.Q(('quantity_unit', ''), _negated=True)), _connector='OR'), name='pricing_quantity_pair'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('validity_interval', ''), ('validity_interval_count__isnull', True)), models.Q(('validity_interval_count__gt', 0), models.Q(('validity_interval', ''), _negated=True)), _connector='OR'), name='pricing_validity_pair'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(('age_from__isnull', True), ('age_to__isnull', True), ('age_from__lte', models.F('age_to')), _connector='OR'), name='pricing_age_order'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(('min_people__isnull', True), ('max_people__isnull', True), ('min_people__lte', models.F('max_people')), _connector='OR'), name='pricing_people_order'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_from__lte', models.F('valid_until')), _connector='OR'), name='pricing_date_order'),
        ),
        migrations.AddConstraint(
            model_name='pricingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('charge_role', 'addon'), ('product_type', 'addon')), models.Q(('charge_role', 'registration_fee'), ('product_type', 'registration_fee')), models.Q(('charge_role', 'deposit'), ('product_type', 'deposit')), models.Q(('charge_role', 'primary'), models.Q(('product_type__in', ('addon', 'registration_fee', 'deposit')), _negated=True)), _connector='OR'), name='pricing_charge_role'),
        ),
    ]
