# Generated by Django 6.0.2 on 2026-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_pricingplan_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_categories_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px, до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока категорий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB.', null=True, upload_to='site/', verbose_name='Фон нижнего призыва (CTA)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_map_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px, до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока карты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_recommended_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px, до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока рекомендаций'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_steps_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px, до 1 MB.', null=True, upload_to='site/', verbose_name="Фон блока 'Как это работает'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_trust_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px, до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока преимуществ'),
        ),
    ]
