# Generated by Django 6.0.2 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_sitesettings_home_categories_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px (пропорция ~16:5), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон подвала сайта (Footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_background_image',
            field=models.FileField(blank=True, help_text='Рекомендуется PNG/WebP/JPG 1600x120 px (пропорция ~13:1), до 500 KB.', null=True, upload_to='site/', verbose_name='Фон шапки сайта (Header)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_categories_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_cta_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px (пропорция ~16:5), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон нижнего призыва (CTA)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон главного баннера'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_map_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока карты'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_recommended_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока рекомендаций'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_steps_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name="Фон блока 'Как это работает'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_trust_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x600 px (пропорция ~8:3), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон блока преимуществ'),
        ),
    ]
