# Generated by Django 6.0.2 on 2026-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_sitesettings_footer_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name="Баннер страницы 'О проекте' (мобильный)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name='Баннер каталога (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name='Баннер личного кабинета (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x1000 px (пропорция ~4:5, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон подвала сайта (Footer, мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='for_business_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name='Баннер страницы владельцам (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_background_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется PNG/WebP/JPG 800x160 px (пропорция ~5:1, полоса), до 300 KB.', null=True, upload_to='site/', verbose_name='Фон шапки сайта (Header, мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_categories_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон блока категорий (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон нижнего призыва (CTA, мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x1000 px (пропорция ~4:5, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон главного баннера (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_map_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон блока карты (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_recommended_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон блока рекомендаций (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_steps_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name="Фон блока 'Как это работает' (мобильный)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_trust_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x900 px (пропорция ~8:9, вертикальная), до 800 KB.', null=True, upload_to='site/', verbose_name='Фон блока преимуществ (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name='Баннер страницы отзывов (мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_background_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x1400 px (пропорция ~4:7, вертикальная), до 1 MB.', null=True, upload_to='site/', verbose_name='Фон всего сайта (мобильный)'),
        ),
    ]
