# Generated by Django 6.0.2 on 2026-08-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_sitesettings_about_hero_mobile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('audit_type', models.CharField(choices=[('full', 'Полный аудит'), ('technical', 'Технический аудит'), ('content', 'Контентный аудит'), ('schema', 'Аудит Schema.org'), ('links', 'Аудит внутренних ссылок'), ('sitemap', 'Аудит Sitemap')], default='full', max_length=30, verbose_name='Тип проверки')),
                ('total_urls', models.PositiveIntegerField(default=0, verbose_name='Проверено URL')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='Предупреждений')),
                ('auto_fix_count', models.PositiveIntegerField(default=0, verbose_name='Автоисправлений')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('code_version', models.CharField(blank=True, max_length=100, verbose_name='Версия кода')),
                ('environment', models.CharField(default='production', max_length=50, verbose_name='Окружение')),
                ('summary_notes', models.TextField(blank=True, verbose_name='Заметки и итоги')),
            ],
            options={
                'verbose_name': 'Запуск SEO-аудита',
                'verbose_name_plural': 'Запуски SEO-аудитов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, verbose_name='URL страницы')),
                ('page_type', models.CharField(default='other', max_length=50, verbose_name='Тип страницы')),
                ('language', models.CharField(default='all', max_length=10, verbose_name='Язык')),
                ('issue_code', models.CharField(db_index=True, max_length=100, verbose_name='Код проблемы')),
                ('severity', models.CharField(choices=[('critical', 'Критическая'), ('warning', 'Предупреждение'), ('info', 'Информирование')], default='warning', max_length=20, verbose_name='Важность')),
                ('level', models.CharField(choices=[('A', 'Level A (Safe Auto-Fix)'), ('B', 'Level B (Draft / Approval Required)'), ('C', 'Level C (Manual Review Only)')], default='A', max_length=5, verbose_name='Уровень автоматизации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('current_value', models.TextField(blank=True, verbose_name='Текущее значение')),
                ('proposed_value', models.TextField(blank=True, verbose_name='Предлагаемое значение')),
                ('rationale', models.TextField(blank=True, verbose_name='Причина / Обоснование')),
                ('expected_impact', models.TextField(blank=True, verbose_name='Ожидаемый эффект')),
                ('risk_assessment', models.TextField(blank=True, verbose_name='Оценка риска')),
                ('rollback_instructions', models.TextField(blank=True, verbose_name='Способ отката')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения')),
                ('last_checked_at', models.DateTimeField(auto_now=True, verbose_name='Дата последней проверки')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('fixed', 'Исправлена'), ('resolved', 'Решена')], default='open', max_length=20, verbose_name='Статус')),
                ('is_auto_fixable', models.BooleanField(default=False, verbose_name='Авто-исправление (Level A)')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требует подтверждения (Level B)')),
                ('audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='catalog.seoauditrun', verbose_name='Запуск аудита')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_issues', to='catalog.place', verbose_name='Связанное заведение')),
            ],
            options={
                'verbose_name': 'SEO-проблема',
                'verbose_name_plural': 'SEO-проблемы',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_summary', models.CharField(max_length=500, verbose_name='Что изменено')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('source', models.CharField(default='safe_auto_fix', max_length=50, verbose_name='Источник изменения')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('recheck_result', models.CharField(blank=True, max_length=200, verbose_name='Результат повторной проверки')),
                ('is_reversible', models.BooleanField(default=True, verbose_name='Возможность отката')),
                ('is_rolled_back', models.BooleanField(default=False, verbose_name='Откачено')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отката')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='catalog.seoissue', verbose_name='Связанная SEO-проблема')),
            ],
            options={
                'verbose_name': 'Запись изменения SEO',
                'verbose_name_plural': 'Записи изменений SEO',
                'ordering': ['-applied_at'],
            },
        ),
    ]
