# Generated by Django 6.0.2 on 2026-08-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0089_seoauditrun_seoissue_seochange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoissue',
            name='audit_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='catalog.seoauditrun', verbose_name='Запуск аудита'),
        ),
    ]
