# Generated by Django 6.0.2 on 2026-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_seoissue_cascade_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='custom_price_badge_az',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Надпись цены на карточке (AZ)'),
        ),
        migrations.AddField(
            model_name='place',
            name='custom_price_badge_en',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Надпись цены на карточке (EN)'),
        ),
        migrations.AddField(
            model_name='place',
            name='custom_price_badge_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Надпись цены на карточке (RU)'),
        ),
    ]
