# Generated by Django 6.0.2 on 2026-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_backfill_place_scoped_team_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelevent',
            name='event_type',
            field=models.CharField(choices=[('catalog_search', 'Поиск в каталоге'), ('catalog_filter', 'Применение фильтров'), ('place_open', 'Открытие карточки'), ('cta_call', 'Клик: Позвонить'), ('cta_whatsapp', 'Клик: WhatsApp'), ('cta_instagram', 'Клик: Instagram'), ('favorite_toggle', 'Добавление в избранное'), ('review_submit', 'Отправка отзыва'), ('claim_place_start', 'Начало заявки на управление'), ('claim_place_submit', 'Отправка заявки на управление'), ('add_place_signup_start', 'Начало регистрации для добавления места'), ('add_place_signup_complete', 'Завершение регистрации для добавления места'), ('ai_referral_visit', 'Переход из AI-сервиса'), ('owner_signup_start', 'Начало регистрации владельца (архив)'), ('owner_signup_complete', 'Завершение регистрации владельца (архив)')], db_index=True, max_length=32, verbose_name='Событие'),
        ),
    ]
