# Generated by Django 6.0.2 on 2026-08-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_funnelevent_add_place_signup_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placechangeaudit',
            name='source',
            field=models.CharField(choices=[('OWNER_PANEL', 'Управление местами'), ('ADMIN', 'Админка'), ('SYSTEM', 'Система')], db_index=True, default='OWNER_PANEL', max_length=24, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='for_business_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 1 MB. Используется на странице добавления места.', null=True, upload_to='site/', verbose_name='Баннер страницы «Добавить место»'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='for_business_hero_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 800x500 px (пропорция ~8:5), до 600 KB.', null=True, upload_to='site/', verbose_name='Баннер страницы «Добавить место» (мобильный)'),
        ),
    ]
