# Generated by Django 6.0.2 on 2026-08-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_place_schedule_modes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owner_permissions_override',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owner_role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
