# Generated by Django 6.0.2 on 2026-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0098_replace_legacy_gmail_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='schedule_mode',
            field=models.CharField(choices=[('regular', 'Регулярное по дням недели'), ('always_open', 'Круглосуточно / 24/7'), ('by_appointment', 'По предварительной записи'), ('variable', 'Расписание меняется'), ('events', 'По мероприятиям')], default='regular', max_length=20, verbose_name='Тип расписания'),
        ),
    ]
