# Generated by Django 6.0.2 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0099_alter_place_schedule_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price_mode',
            field=models.CharField(choices=[('tariffs', 'Есть тарифы'), ('free', 'Бесплатно'), ('free_entry_paid_services', 'Бесплатный вход + платные услуги'), ('events', 'Цена зависит от мероприятия')], db_index=True, default='tariffs', max_length=32, verbose_name='Режим цены'),
        ),
    ]
