# Generated by Django 6.0.2 on 2026-09-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0101_unique_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPlaceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('base_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Нужны исправления')], db_index=True, default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_revisions', to=settings.AUTH_USER_MODEL)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_revision', to='catalog.place')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_volunteer_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изменения волонтёра',
                'verbose_name_plural': 'Изменения волонтёров',
            },
        ),
    ]
