# Generated by Django 6.0.2 on 2026-09-13 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_staff_role_audit_and_superadmin_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeownershiprequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='specialistreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='AccountDeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_reference', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('policy_version', models.CharField(max_length=64)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('retain_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['subject_reference', 'created_at'], name='acct_del_subject_audit_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрошено'), ('CONFIRMATION_SENT', 'Код подтверждения отправлен'), ('SCHEDULED', 'Запланировано'), ('CANCELED', 'Отменено'), ('HELD', 'Приостановлено'), ('PROCESSING', 'Выполняется'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], db_index=True, default='REQUESTED', max_length=24)),
                ('policy_version', models.CharField(max_length=64)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('confirmation_code_hash', models.CharField(blank=True, default='', max_length=255)),
                ('confirmation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_attempts_left', models.PositiveSmallIntegerField(default=0)),
                ('code_purpose', models.CharField(blank=True, choices=[('DELETE', 'Подтверждение удаления'), ('CANCEL', 'Подтверждение отмены')], default='', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hold_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scheduled_for', 'id'),
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='acct_del_status_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('REQUESTED', 'CONFIRMATION_SENT', 'SCHEDULED', 'HELD', 'PROCESSING')), ('user__isnull', False)), fields=('user',), name='unique_active_account_deletion')],
            },
        ),
    ]
