# Generated by Django 6.0.2 on 2026-09-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0113_place_localized_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-created_at',), 'permissions': [('override_place_location', 'Can override coordinate-based place location')], 'verbose_name': 'Постоянное место', 'verbose_name_plural': 'Постоянные места'},
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='place',
            name='location_dataset_version',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='place',
            name='location_resolution_status',
            field=models.CharField(default='legacy', editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name='PlaceLocationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=1000)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('automatic_city', models.CharField(blank=True, max_length=100)),
                ('automatic_district', models.CharField(blank=True, max_length=100)),
                ('automatic_status', models.CharField(max_length=32)),
                ('dataset_version', models.CharField(blank=True, max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_overrides', to='catalog.place')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('place',), name='one_current_location_override')],
            },
        ),
    ]
