# Generated by Django 6.0.2 on 2026-09-29 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0116_moderation_sla_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPlaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('relationship_kind', models.CharField(choices=[('business', 'Бизнес'), ('informational', 'Информационная связь')], default='business', max_length=16)),
                ('base_place_ownership_version', models.PositiveBigIntegerField(default=1)),
                ('base_organization_ownership_version', models.PositiveBigIntegerField(default=1)),
                ('base_place_content_version', models.PositiveBigIntegerField(default=1)),
                ('place_owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('organization_owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceVenueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('base_place_content_version', models.PositiveBigIntegerField(default=1)),
                ('base_location_content_version', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_az', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_az', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='content_version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='place',
            name='nature',
            field=models.CharField(blank=True, choices=[('business', 'Бизнес'), ('public_space', 'Общественное место')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='nature_approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='operating_state',
            field=models.CharField(blank=True, choices=[('open', 'Открыто'), ('closed', 'Закрыто')], editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='operating_state_approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='ownership_version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='place',
            name='venue_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_az', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('supplement_az', models.TextField(blank=True, default='')),
                ('supplement_ru', models.TextField(blank=True, default='')),
                ('supplement_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16)),
                ('source_program_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('program_snapshot', models.JSONField(blank=True, default=dict)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='catalog.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_az', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('confirmed_at', models.DateTimeField()),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_physical_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='confirmed_location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='catalog.location'),
        ),
        migrations.CreateModel(
            name='OfferingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_az', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lesson_format', models.CharField(blank=True, choices=[('group', 'Групповой'), ('individual', 'Индивидуальный')], default='', max_length=16)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('schedule_text', models.TextField(blank=True, default='')),
                ('teachers_text', models.TextField(blank=True, default='')),
                ('conditions_az', models.TextField(blank=True, default='')),
                ('conditions_ru', models.TextField(blank=True, default='')),
                ('conditions_en', models.TextField(blank=True, default='')),
                ('conditions_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_groups', to='catalog.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_az', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_az', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ownership_version', models.PositiveBigIntegerField(default=1, editable=False)),
                ('ownership_verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL)),
                ('ownership_verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='catalog.organization'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1), ('ownership_version__gte', 1)), name='place_structure_versions_positive'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nature__isnull', True), ('nature_approved_at__isnull', True)), models.Q(('nature__in', ['business', 'public_space']), ('nature__isnull', False), ('nature_approved_at__isnull', False)), _connector='OR'), name='place_nature_approval_pair'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operating_state__isnull', True), ('operating_state_approved_at__isnull', True)), models.Q(('operating_state__in', ['open', 'closed']), ('operating_state__isnull', False), ('operating_state_approved_at__isnull', False)), _connector='OR'), name='place_operating_approval_pair'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_location__isnull', True), ('venue_confirmed_at__isnull', True)), models.Q(('confirmed_location__isnull', False), ('venue_confirmed_at__isnull', False)), _connector='OR'), name='place_venue_confirmation_pair'),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_requests', to='catalog.organization'),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_requests', to='catalog.place'),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placevenuerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placevenuerequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_requests', to='catalog.location'),
        ),
        migrations.AddField(
            model_name='placevenuerequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_requests', to='catalog.place'),
        ),
        migrations.AddField(
            model_name='placevenuerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='catalog.organization'),
        ),
        migrations.AddField(
            model_name='activity',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='catalog.program'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_activities', to='catalog.program'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='location_content_positive'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', True), ('lng__isnull', True)), models.Q(('lat__gte', -90), ('lat__isnull', False), ('lat__lte', 90), ('lng__gte', -180), ('lng__isnull', False), ('lng__lte', 180)), _connector='OR'), name='location_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address', ''), _negated=True), models.Q(('lat__isnull', False), ('lng__isnull', False)), _connector='OR'), name='location_physical_identity'),
        ),
        migrations.AddConstraint(
            model_name='offeringgroup',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='offeringgroup_content_positive'),
        ),
        migrations.AddConstraint(
            model_name='offeringgroup',
            constraint=models.CheckConstraint(condition=models.Q(('age_from__isnull', True), ('age_to__isnull', True), ('age_from__lte', models.F('age_to')), _connector='OR'), name='offering_group_age_order'),
        ),
        migrations.AddConstraint(
            model_name='offeringgroup',
            constraint=models.CheckConstraint(condition=models.Q(('lesson_format__in', ('', 'group', 'individual'))), name='offering_group_format_known'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='organization_content_positive'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'published', 'rejected'])), name='organization_publication_state'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_version__gte', 1)), name='organization_ownership_positive'),
        ),
        migrations.AddConstraint(
            model_name='organizationplacerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('status__in', ('approved', 'rejected', 'canceled'))), _connector='OR'), name='organizationplacerequest_decision_pair'),
        ),
        migrations.AddConstraint(
            model_name='organizationplacerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('place', 'organization'), name='organization_place_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationplacerequest',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_kind__in', ('business', 'informational'))), name='organization_place_kind_known'),
        ),
        migrations.AddConstraint(
            model_name='organizationplacerequest',
            constraint=models.CheckConstraint(condition=models.Q(('base_organization_ownership_version__gte', 1), ('base_place_content_version__gte', 1), ('base_place_ownership_version__gte', 1)), name='organization_place_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='placevenuerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('status__in', ('approved', 'rejected', 'canceled'))), _connector='OR'), name='placevenuerequest_decision_pair'),
        ),
        migrations.AddConstraint(
            model_name='placevenuerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('place',), name='place_venue_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='placevenuerequest',
            constraint=models.CheckConstraint(condition=models.Q(('base_location_content_version__gte', 1), ('base_place_content_version__gte', 1)), name='place_venue_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='program_content_positive'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'published', 'rejected'])), name='program_publication_state'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__gte', 1)), name='activity_content_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'published', 'rejected'])), name='activity_publication_state'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_program__isnull', True), ('source_program_version__isnull', True)), models.Q(('source_program__isnull', False), ('source_program_version__gte', 1), ('source_program_version__isnull', False)), _connector='OR'), name='activity_provenance_pair'),
        ),
    ]
