# Generated by Django 6.0.2 on 2026-09-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0117_task33_catalog_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOwnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена')], db_index=True, default='PENDING', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('moderation_note', models.TextField(blank=True, default='')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('base_ownership_version', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('base_owner_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='description_az',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='base_organization_owner_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationplacerequest',
            name='base_place_owner_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organization_join_org_ownership_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organization_join_place_ownership_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='organization_relationship_kind',
            field=models.CharField(blank=True, choices=[('business', 'Бизнес'), ('informational', 'Информационная связь')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='placeownershiprequest',
            name='base_owner_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='placeownershiprequest',
            name='base_ownership_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='placeownershiprequest',
            name='request_kind',
            field=models.CharField(choices=[('CLAIM', 'Владение'), ('PUBLICATION', 'Публикация')], default='CLAIM', editable=False, max_length=16),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization_join_org_ownership_version__isnull', True), ('organization_join_place_ownership_version__isnull', True), ('organization_relationship_kind__isnull', True)), models.Q(('organization__isnull', False), ('organization_join_org_ownership_version__gte', 1), ('organization_join_org_ownership_version__isnull', False), ('organization_join_place_ownership_version__gte', 1), ('organization_join_place_ownership_version__isnull', False), ('organization_relationship_kind__in', ('business', 'informational')), ('organization_relationship_kind__isnull', False)), _connector='OR'), name='place_affiliation_confirmation_pair'),
        ),
        migrations.AddConstraint(
            model_name='placeownershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_kind__in', ('CLAIM', 'PUBLICATION'))), name='place_claim_kind_known'),
        ),
        migrations.AddConstraint(
            model_name='placeownershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('base_ownership_version__isnull', True), ('base_ownership_version__gte', 1), _connector='OR'), name='place_claim_base_positive'),
        ),
        migrations.AddField(
            model_name='organizationownershiprequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_ownership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationownershiprequest',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_ownership_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationownershiprequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_requests', to='catalog.organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationownershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'applicant'), name='org_ownership_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='organizationownershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('base_ownership_version__isnull', True), ('base_ownership_version__gte', 1), _connector='OR'), name='org_claim_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='organizationownershiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'APPROVED', 'REJECTED'))), name='org_claim_status_known'),
        ),
    ]
