# Generated by Django 6.0.2 on 2026-09-29 10:56

import catalog.models.business_team
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0118_task33_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerteaminvitation',
            name='actions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ownerteaminvitation',
            name='base_grant_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerteaminvitation',
            name='base_ownership_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerteaminvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerteammembership',
            name='actions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ownerteammembership',
            name='base_ownership_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerteammembership',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OrganizationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ownership_version', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Модератор'), ('EDITOR', 'Редактор')], default='EDITOR', max_length=16)),
                ('actions', models.JSONField(default=list)),
                ('scope', models.CharField(choices=[('selected_places', 'Selected places'), ('all_network', 'All network')], default='selected_places', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_grants', to='catalog.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_team_grants', to=settings.AUTH_USER_MODEL)),
                ('selected_places', models.ManyToManyField(blank=True, related_name='selected_organization_grants', to='catalog.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'member'), name='org_team_member_unique'), models.CheckConstraint(condition=models.Q(('owner', models.F('member')), _negated=True), name='org_team_not_owner'), models.CheckConstraint(condition=models.Q(('base_ownership_version__gte', 1), ('version__gte', 1)), name='org_team_versions_positive'), models.CheckConstraint(condition=models.Q(('scope__in', ['selected_places', 'all_network'])), name='org_team_scope_known')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Модератор'), ('EDITOR', 'Редактор')], default='EDITOR', max_length=16)),
                ('actions', models.JSONField(default=list)),
                ('scope', models.CharField(choices=[('selected_places', 'Selected places'), ('all_network', 'All network')], max_length=24)),
                ('selected_place_ids', models.JSONField(default=list)),
                ('scope_snapshot', models.JSONField(default=dict)),
                ('base_ownership_version', models.PositiveBigIntegerField()),
                ('base_grant_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(default=catalog.models.business_team.invitation_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='catalog.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_organization_team_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'email'), name='org_team_pending_email_unique'), models.CheckConstraint(condition=models.Q(('base_ownership_version__gte', 1)), name='org_invite_base_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED'])), name='org_invite_status_known'), models.CheckConstraint(condition=models.Q(('scope__in', ['selected_places', 'all_network'])), name='org_invite_scope_known')],
            },
        ),
    ]
