# Generated by Django 6.0.2 on 2026-09-29 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0119_task33_business_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_revision', to='catalog.activity'),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='base_content_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='dependencies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='offering_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_revision', to='catalog.offeringgroup'),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_revision', to='catalog.organization'),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_revision', to='catalog.program'),
        ),
        migrations.AddField(
            model_name='volunteerplacerevision',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='volunteerplacerevision',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_revision', to='catalog.place'),
        ),
        migrations.AddConstraint(
            model_name='volunteerplacerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('offering_group__isnull', True), ('organization__isnull', True), ('place__isnull', False), ('program__isnull', True)), models.Q(('activity__isnull', True), ('offering_group__isnull', True), ('organization__isnull', False), ('place__isnull', True), ('program__isnull', True)), models.Q(('activity__isnull', True), ('offering_group__isnull', True), ('organization__isnull', True), ('place__isnull', True), ('program__isnull', False)), models.Q(('activity__isnull', False), ('offering_group__isnull', True), ('organization__isnull', True), ('place__isnull', True), ('program__isnull', True)), models.Q(('activity__isnull', True), ('offering_group__isnull', False), ('organization__isnull', True), ('place__isnull', True), ('program__isnull', True)), _connector='OR'), name='publication_revision_one_target'),
        ),
        migrations.AddConstraint(
            model_name='volunteerplacerevision',
            constraint=models.CheckConstraint(condition=models.Q(('base_content_version__gte', 1), ('schema_version__gte', 1)), name='publication_revision_versions_positive'),
        ),
    ]
