# Generated by Django 6.0.2 on 2026-09-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0120_task33_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeownershiprequest',
            name='base_candidate_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='placeownershiprequest',
            name='base_content_version',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
