# Generated by Django 6.0.2 on 2026-10-03 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models



def preserve_review_sources(apps, schema_editor):
    """Frozen historical models: no live signals, row deletion or invented timestamps."""
    alias = schema_editor.connection.alias
    for name, target in [('PlaceReview', 'place'), ('SpecialistReview', 'specialist')]:
        sources = apps.get_model('catalog', name)
        revisions = apps.get_model('catalog', name + 'Revision')
        groups = {}
        for source in sources.objects.using(alias).order_by('pk').iterator():
            values = {field: getattr(source, field, default) for field, default in {
                'author_name': '', 'is_anonymous': False, 'rating': 5, 'text': '',
                'contains_profanity': False, 'status': 'pending', 'submitted_at': None,
                'moderated_at': None, 'moderated_by_id': None, 'rejection_reason': '',
                'created_at': source.created_at, 'source_is_approved': source.is_approved,
            }.items()}
            revision, created = revisions.objects.using(alias).get_or_create(review_id=source.pk, is_baseline=True, defaults=values)
            approved = source.status == 'approved' and source.is_approved
            field = 'current_revision_id' if approved else 'candidate_revision_id'
            if created:
                sources.objects.using(alias).filter(pk=source.pk).update(**{field: revision.pk})
            if name == 'PlaceReview':
                reactions = apps.get_model('catalog', 'PlaceReviewReaction')
                reactions.objects.using(alias).filter(review_id=source.pk, revision__isnull=True).update(revision_id=revision.pk)
            # Re-running must never reactivate anonymized archived siblings.
            if not source.is_current and source.archive_head_id:
                continue
            identity = (getattr(source, target + '_id'), source.user_id if source.user_id else ('unknown', source.pk))
            groups.setdefault(identity, []).append(source)
        for rows in groups.values():
            head = max(rows, key=lambda item: (item.status == 'approved' and item.is_approved, item.moderated_at or item.created_at, item.pk))
            sources.objects.using(alias).filter(pk__in=[r.pk for r in rows if r.pk != head.pk]).update(is_current=False, archive_head_id=head.pk)
            sources.objects.using(alias).filter(pk=head.pk).update(is_current=True, archive_head_id=None)

def drain_deferred_foreign_keys(apps, schema_editor):
    """Historical PostgreSQL rows must pass FK checks before constraint DDL."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0127_task33_workflow_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], db_index=True, default='pending', max_length=16)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('value', models.SmallIntegerField(choices=[(1, 'Р›Р°Р№Рє'), (-1, 'Р”РёР·Р»Р°Р№Рє')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_baseline', models.BooleanField(default=False)),
                ('source_is_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], db_index=True, default='pending', max_length=16)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('value', models.SmallIntegerField(choices=[(1, 'Р›Р°Р№Рє'), (-1, 'Р”РёР·Р»Р°Р№Рє')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_baseline', models.BooleanField(default=False)),
                ('source_is_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_baseline', models.BooleanField(default=False)),
                ('source_is_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('value', models.SmallIntegerField(choices=[(1, 'Р›Р°Р№Рє'), (-1, 'Р”РёР·Р»Р°Р№Рє')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('contains_profanity', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'РќР° РјРѕРґРµСЂР°С†РёРё'), ('approved', 'РћРґРѕР±СЂРµРЅ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅ')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_baseline', models.BooleanField(default=False)),
                ('source_is_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='placereviewreaction',
            name='unique_place_review_reaction_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='placereviewreaction',
            name='unique_place_review_reaction_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='specialistreview',
            name='unique_specialist_review_per_user',
        ),
        migrations.AddField(
            model_name='placereview',
            name='archive_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sources', to='catalog.placereview'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='archive_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sources', to='catalog.specialistreview'),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='contains_profanity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='session_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.activity'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='archive_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sources', to='catalog.activityreview'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.activityreview'),
        ),
        migrations.AddField(
            model_name='activityreviewreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreviewrevision',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.activityreview'),
        ),
        migrations.AddField(
            model_name='activityreviewreaction',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.activityreviewrevision'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='candidate_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.activityreviewrevision'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.activityreviewrevision'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='archive_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sources', to='catalog.eventreview'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.event'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.eventreview'),
        ),
        migrations.AddField(
            model_name='eventreviewreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreviewrevision',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.eventreview'),
        ),
        migrations.AddField(
            model_name='eventreviewreaction',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.eventreviewrevision'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='candidate_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.eventreviewrevision'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.eventreviewrevision'),
        ),
        migrations.AddField(
            model_name='placereviewrevision',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placereviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.placereview'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='candidate_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.placereviewrevision'),
        ),
        migrations.AddField(
            model_name='placereview',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.placereviewrevision'),
        ),
        migrations.AddField(
            model_name='placereviewreaction',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.placereviewrevision'),
        ),
        migrations.AddField(
            model_name='specialistreviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.specialistreview'),
        ),
        migrations.AddField(
            model_name='specialistreviewreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistreviewrevision',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistreviewrevision',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.specialistreview'),
        ),
        migrations.AddField(
            model_name='specialistreviewreaction',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.specialistreviewrevision'),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='candidate_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.specialistreviewrevision'),
        ),
        migrations.AddField(
            model_name='specialistreview',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.specialistreviewrevision'),
        ),
        migrations.RunPython(preserve_review_sources),
        migrations.RunPython(drain_deferred_foreign_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='placereview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('user__isnull', False)), fields=('place', 'user'), name='placereview_current_user'),
        ),
        migrations.AddConstraint(
            model_name='placereviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('revision', 'session_key'), name='unique_place_review_reaction_per_session'),
        ),
        migrations.AddConstraint(
            model_name='placereviewreaction',
            constraint=models.UniqueConstraint(fields=('revision', 'user'), name='unique_place_review_reaction_per_user'),
        ),
        migrations.AddConstraint(
            model_name='specialistreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('user__isnull', False)), fields=('specialist', 'user'), name='specialistreview_current_user'),
        ),
        migrations.AddConstraint(
            model_name='activityreviewrevision',
            constraint=models.CheckConstraint(condition=models.Q(('is_baseline', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='activityreviewrevision_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='activityreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('revision', 'user'), name='activityreviewreaction_user'),
        ),
        migrations.AddConstraint(
            model_name='activityreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('revision', 'session_key'), name='activityreviewreaction_session'),
        ),
        migrations.AddConstraint(
            model_name='activityreviewreaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='activityreviewreaction_value'),
        ),
        migrations.AddConstraint(
            model_name='activityreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('user__isnull', False)), fields=('activity', 'user'), name='activityreview_current_user'),
        ),
        migrations.AddConstraint(
            model_name='eventreviewrevision',
            constraint=models.CheckConstraint(condition=models.Q(('is_baseline', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='eventreviewrevision_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='eventreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('revision', 'user'), name='eventreviewreaction_user'),
        ),
        migrations.AddConstraint(
            model_name='eventreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('revision', 'session_key'), name='eventreviewreaction_session'),
        ),
        migrations.AddConstraint(
            model_name='eventreviewreaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='eventreviewreaction_value'),
        ),
        migrations.AddConstraint(
            model_name='eventreview',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('user__isnull', False)), fields=('event', 'user'), name='eventreview_current_user'),
        ),
        migrations.AddConstraint(
            model_name='placereviewrevision',
            constraint=models.CheckConstraint(condition=models.Q(('is_baseline', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='placereviewrevision_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='specialistreviewrevision',
            constraint=models.CheckConstraint(condition=models.Q(('is_baseline', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='specialistreviewrevision_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='specialistreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('revision', 'user'), name='specialistreviewreaction_user'),
        ),
        migrations.AddConstraint(
            model_name='specialistreviewreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('revision', 'session_key'), name='specialistreviewreaction_session'),
        ),
        migrations.AddConstraint(
            model_name='specialistreviewreaction',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='specialistreviewreaction_value'),
        ),
    ]
