# Generated by Django 6.0.2 on 2026-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0128_task33_review_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='activityreviewreaction',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')]),
        ),
        migrations.AlterField(
            model_name='activityreviewrevision',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventreviewreaction',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')]),
        ),
        migrations.AlterField(
            model_name='eventreviewrevision',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='placereviewrevision',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='specialistreviewreaction',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')]),
        ),
        migrations.AlterField(
            model_name='specialistreviewrevision',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=16),
        ),
    ]
