# Generated by Django 6.0.2 on 2026-10-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0129_task33_review_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('report', 'Report')], max_length=8)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('report', 'Report')], max_length=8)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('report', 'Report')], max_length=8)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('report', 'Report')], max_length=8)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='placereviewreaction',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='catalog.placereviewrevision'),
        ),
        migrations.AddConstraint(
            model_name='activityreviewrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('review',), name='activityreviewrevision_one_baseline'),
        ),
        migrations.AddConstraint(
            model_name='eventreviewrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('review',), name='eventreviewrevision_one_baseline'),
        ),
        migrations.AddConstraint(
            model_name='placereviewrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('review',), name='placereviewrevision_one_baseline'),
        ),
        migrations.AddConstraint(
            model_name='specialistreviewrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('review',), name='specialistreviewrevision_one_baseline'),
        ),
        migrations.AddField(
            model_name='activityreviewresponse',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreviewresponse',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='catalog.activityreviewrevision'),
        ),
        migrations.AddField(
            model_name='eventreviewresponse',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreviewresponse',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='catalog.eventreviewrevision'),
        ),
        migrations.AddField(
            model_name='placereviewresponse',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placereviewresponse',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='catalog.placereviewrevision'),
        ),
        migrations.AddField(
            model_name='specialistreviewresponse',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistreviewresponse',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='catalog.specialistreviewrevision'),
        ),
    ]
