# Generated by Django 6.0.2 on 2026-10-03 13:17

import catalog.private_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0130_task33_review_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ('-created_at',), 'permissions': [('review_specialist_claim', 'Can verify specialist person claims')], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='specialistdocument',
            options={'permissions': [('review_specialist_documents', 'Can review private specialist documents')], 'verbose_name': 'Документ специалиста', 'verbose_name_plural': 'Документы специалиста'},
        ),
        migrations.AddField(
            model_name='specialist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_specialists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialist',
            name='person_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='verified_person_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_specialist_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialistdocument',
            name='opted_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialistdocument',
            name='opted_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_document_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialistdocument',
            name='file',
            field=models.FileField(storage=catalog.private_storage.SpecialistPrivateStorage(), upload_to=catalog.private_storage.specialist_document_path, verbose_name='Файл документа'),
        ),
        migrations.CreateModel(
            name='SpecialistEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('organization_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialist_employments', to='catalog.organization')),
                ('organization_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_links', to='catalog.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistEmploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='catalog.specialistemployment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpecialistClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_claims', to=settings.AUTH_USER_MODEL)),
                ('previous_legacy_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_claims', to='catalog.specialist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('applicant__isnull', False), ('status', 'pending')), fields=('specialist', 'applicant'), name='spec_claim_pending_applicant'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'approved', 'rejected', 'withdrawn'))), name='spec_claim_valid_status'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='spec_claim_positive_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='spec_employment_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.CheckConstraint(condition=models.Q(('role', ''), _negated=True), name='spec_employment_role_required'),
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'active', 'cancelled'))), name='spec_employment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='spec_employment_positive_ver'),
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('organization_confirmed_at__isnull', False), ('person_confirmed_at__isnull', False)), _connector='OR'), name='spec_employment_active_consents'),
        ),
    ]
