# Generated by Django 6.0.2 on 2026-10-03 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0131_task33_specialist_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistemployment',
            name='organization_ownership_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='specialistemployment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'active'))), fields=('specialist', 'organization', 'role', 'start_date', 'end_date'), name='spec_employment_exact_open_unique', nulls_distinct=False),
        ),
    ]
