# Generated by Django 6.0.2 on 2026-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0137_organization_connection_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationgrant',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Наблюдатель'), ('EDITOR', 'Редактор')], default='EDITOR', max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationgrant',
            name='scope',
            field=models.CharField(choices=[('selected_places', 'Выбранные филиалы'), ('all_network', 'Вся сеть, включая будущие филиалы')], default='selected_places', max_length=24),
        ),
        migrations.AlterField(
            model_name='organizationteaminvitation',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Наблюдатель'), ('EDITOR', 'Редактор')], default='EDITOR', max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationteaminvitation',
            name='scope',
            field=models.CharField(choices=[('selected_places', 'Выбранные филиалы'), ('all_network', 'Вся сеть, включая будущие филиалы')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ownerteammembership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Наблюдатель'), ('EDITOR', 'Редактор')], db_index=True, default='EDITOR', max_length=16, verbose_name='Роль в команде'),
        ),
        migrations.AlterField(
            model_name='ownerteaminvitation',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Менеджер'), ('MODERATOR', 'Наблюдатель'), ('EDITOR', 'Редактор')], db_index=True, default='EDITOR', max_length=16, verbose_name='Роль в команде'),
        ),
    ]
