# Generated by Django 6.0.2 on 2026-10-07 12:02

import catalog.models.specialist_proposal_draft
import catalog.private_storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0139_connection_receipt_actor_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistProposalDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('photo', models.FileField(blank=True, storage=catalog.private_storage.SpecialistPrivateStorage(), upload_to=catalog.models.specialist_proposal_draft.proposal_photo_path)),
                ('photo_content_type', models.CharField(blank=True, max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_proposal_drafts', to=settings.AUTH_USER_MODEL)),
                ('submitted_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_working_copies', to='catalog.specialist')),
            ],
        ),
    ]
