# Generated by Django 6.0.2 on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0066_sitesettings_events_section_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationEvent",
            fields=[],
            options={
                "verbose_name": "Мероприятия на проверке",
                "verbose_name_plural": "Мероприятия на проверке",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.event",),
        ),
        migrations.CreateModel(
            name="ModerationPlace",
            fields=[],
            options={
                "verbose_name": "Места на проверке",
                "verbose_name_plural": "Места на проверке",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.place",),
        ),
        migrations.CreateModel(
            name="ModerationPlaceOwnershipRequest",
            fields=[],
            options={
                "verbose_name": "Заявки владельцев",
                "verbose_name_plural": "Заявки владельцев",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.placeownershiprequest",),
        ),
        migrations.CreateModel(
            name="ModerationReview",
            fields=[],
            options={
                "verbose_name": "Отзывы на проверке",
                "verbose_name_plural": "Отзывы на проверке",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.placereview",),
        ),
        migrations.CreateModel(
            name="ModerationSpecialist",
            fields=[],
            options={
                "verbose_name": "Специалист на проверке",
                "verbose_name_plural": "Специалисты на проверке",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalog.specialist",),
        ),
    ]
