async (page) => {
  const check = (ok, message) => { if (!ok) throw new Error(message); };
  const base = 'http://127.0.0.1:8772/ru/';
  await page.setViewportSize({width:1440,height:1000});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base);
  const rail=page.locator('[data-places-rail]');
  check(await rail.count()===1, 'Expected the places rail on the home page');
  await rail.scrollIntoViewIfNeeded();
  await page.mouse.move(0,0);
  const viewport=rail.locator('[data-rail-viewport]');
  const position=()=>viewport.evaluate(e=>e.scrollLeft);
  await page.waitForTimeout(100);
  const before=await position(); await page.waitForTimeout(400);
  check(await position()>before+2, 'Desktop rail must move');
  const toggle=rail.locator('[data-rail-toggle]');
  await toggle.click(); await page.mouse.move(0,0); await toggle.blur();
  const paused=await position(); await page.waitForTimeout(250);
  check(Math.abs(await position()-paused)<1, 'Pause must stop motion after pointer and focus leave');
  await toggle.click(); await toggle.blur(); await viewport.hover();
  const hovered=await position(); await page.waitForTimeout(250);
  check(Math.abs(await position()-hovered)<1, 'Hover must stop motion');
  await page.mouse.move(0,0);
  const first=rail.locator('[data-rail-original] a').first();
  await first.focus(); await page.keyboard.press('Tab'); await page.keyboard.press('Shift+Tab');
  const focused=await position(); await page.waitForTimeout(250);
  check(Math.abs(await position()-focused)<1, 'Keyboard focus must stop motion');
  check(await first.evaluate(e=>getComputedStyle(e).outlineStyle)!=='none', 'Keyboard focus must be visible');
  await first.blur();
  await page.emulateMedia({reducedMotion:'reduce'}); await page.waitForTimeout(100);
  const reduced=await position(); await page.waitForTimeout(250);
  check(Math.abs(await position()-reduced)<1, 'Reduced motion must stop autoplay');
  check(await rail.locator('[data-rail-copy]').count()===0, 'Reduced motion must remove visual copies');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:390,height:900}); await page.waitForTimeout(100);
  const mobile=await position(); await page.waitForTimeout(400);
  check(await position()>mobile+2, 'Mobile rail must move automatically');
  check(await toggle.isVisible(), 'Mobile must expose a pause control');
  const start=await position();
  await viewport.dispatchEvent('pointerdown', {pointerId:11, pointerType:'touch', clientX:280, clientY:260, button:0});
  await viewport.dispatchEvent('pointermove', {pointerId:11, pointerType:'touch', clientX:120, clientY:260});
  await viewport.dispatchEvent('pointerup', {pointerId:11, pointerType:'touch', clientX:120, clientY:260});
  check(Math.abs((await position())-start)>40, 'Touch swipe must move the mobile rail');
  check(await rail.locator('[data-rail-copy]').count()>0, 'Mobile needs visual copies for continuous autoplay');
  check(await page.locator('.home-recommended').count()===0, 'Do not duplicate recommendations below');
  return {passed:true,checks:12};
}
