# Generated by Django 6.0.2 on 2026-02-24 16:55

from django.db import migrations, models


def create_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    if SiteSettings.objects.exists():
        return
    SiteSettings.objects.create(
        brand_name="KidsMap",
        contacts_text_ru="Свяжитесь с нами по почте: kidsmap@example.com",
        contacts_text_en="Contact us by email: kidsmap@example.com",
        contacts_text_az="Bizimlə e-poçt vasitəsilə əlaqə saxlayın: kidsmap@example.com",
        about_text_ru="KidsMap — каталог детских кружков и секций в Баку.",
        about_text_en="KidsMap is a catalog of kids clubs and courses in Baku.",
        about_text_az="KidsMap Bakıda uşaqlar üçün dərnək və kurs kataloqudur.",
        empty_results_text_ru="Ничего не найдено.",
        empty_results_text_en="Nothing found.",
        empty_results_text_az="Heç nə tapılmadı.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_place_options_placelike"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand_name", models.CharField(default="KidsMap", max_length=120, verbose_name="Название бренда")),
                ("logo", models.FileField(blank=True, null=True, upload_to="site/", verbose_name="Логотип")),
                ("contacts_text_ru", models.TextField(blank=True, default="", verbose_name="Контакты (RU)")),
                ("contacts_text_en", models.TextField(blank=True, default="", verbose_name="Контакты (EN)")),
                ("contacts_text_az", models.TextField(blank=True, default="", verbose_name="Контакты (AZ)")),
                ("about_text_ru", models.TextField(blank=True, default="", verbose_name="О проекте (RU)")),
                ("about_text_en", models.TextField(blank=True, default="", verbose_name="О проекте (EN)")),
                ("about_text_az", models.TextField(blank=True, default="", verbose_name="О проекте (AZ)")),
                (
                    "empty_results_text_ru",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Текст пустого результата (RU)"),
                ),
                (
                    "empty_results_text_en",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Текст пустого результата (EN)"),
                ),
                (
                    "empty_results_text_az",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Текст пустого результата (AZ)"),
                ),
                (
                    "empty_results_image",
                    models.FileField(blank=True, null=True, upload_to="site/", verbose_name="Картинка пустого результата"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.RunPython(create_site_settings, migrations.RunPython.noop),
    ]
