# Generated by Django 6.0.2 on 2026-02-24 17:05

from django.db import migrations, models


def fill_footer_defaults(apps, schema_editor):
    SiteSettings = apps.get_model("catalog", "SiteSettings")
    obj = SiteSettings.objects.order_by("id").first()
    if not obj:
        return
    changed = False
    if not obj.footer_phone:
        obj.footer_phone = "+994 00 000 00 00"
        changed = True
    if not obj.footer_email:
        obj.footer_email = "kidsmap@example.com"
        changed = True
    if not obj.footer_instagram:
        obj.footer_instagram = "kidsmap"
        changed = True
    if changed:
        obj.save(update_fields=["footer_phone", "footer_email", "footer_instagram", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="Email в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_instagram",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Instagram в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_phone",
            field=models.CharField(blank=True, default="", max_length=60, verbose_name="Телефон в футере"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="WhatsApp ссылка в футере"),
        ),
        migrations.RunPython(fill_footer_defaults, migrations.RunPython.noop),
    ]
