# Generated by Django 6.0.2 on 2026-02-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_sitesettings_footer_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAboutSettings',
            fields=[
            ],
            options={
                'verbose_name': 'О проекте',
                'verbose_name_plural': 'О проекте',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteBrandingSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Лого и бренд',
                'verbose_name_plural': 'Лого и бренд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteContactsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteEmptyStateSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Пустой результат',
                'verbose_name_plural': 'Пустой результат',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Футер и соцсети',
                'verbose_name_plural': 'Футер и соцсети',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройка сайта'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1600x500 px, до 350 KB.', null=True, upload_to='site/', verbose_name='Фон главного баннера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_background_image',
            field=models.FileField(blank=True, help_text='Рекомендуется JPG/WebP 1920x1080 px, до 400 KB.', null=True, upload_to='site/', verbose_name='Фон сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='empty_results_image',
            field=models.FileField(blank=True, help_text='Рекомендуется PNG/WebP 600x400 px, до 250 KB.', null=True, upload_to='site/', verbose_name='Картинка пустого результата'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Рекомендуется SVG или PNG, размер 256x256 px (минимум 128x128).', null=True, upload_to='site/', verbose_name='Логотип'),
        ),
    ]
