# Generated by Django 6.0.2 on 2026-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_placelike_unique_place_like_per_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts_json', models.JSONField(blank=True, default=list, verbose_name='Районы (JSON)')),
                ('metro_stations_json', models.JSONField(blank=True, default=list, verbose_name='Станции метро (JSON)')),
                ('seo_pages_json', models.JSONField(blank=True, default=dict, verbose_name='SEO страницы (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контент каталога',
                'verbose_name_plural': 'Контент каталога',
            },
        ),
    ]
