# Generated by Django 6.0.2 on 2026-02-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_catalogcontentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReviewsByClub',
            fields=[
            ],
            options={
                'verbose_name': 'Отзывы по кружкам',
                'verbose_name_plural': 'Отзывы по кружкам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.place',),
        ),
    ]
