# Generated by Django 6.0.2 on 2026-02-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_siteanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Сессия')),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='Просмотры')),
                ('first_path', models.CharField(blank=True, default='', max_length=255, verbose_name='Первый путь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ('-day', '-hits'),
                'constraints': [models.UniqueConstraint(fields=('day', 'session_key'), name='unique_site_visit_per_day_session')],
            },
        ),
    ]
