"""Presentation for the permanent-place form; shared by create and edit."""
from catalog.services.permanent_place_rules import copy as t


def localize_fields(form):
    labels = {
        'category': ('Категория', 'Kateqoriya', 'Category'),
        'nature': ('Тип места', 'Məkan növü', 'Place type'),
        'subcategory': ('Подкатегория', 'Alt kateqoriya', 'Subcategory'),
        'age_from': ('Возраст от', 'Minimum yaş', 'Age from'),
        'age_to': ('Возраст до', 'Maksimum yaş', 'Age to'),
        'offers_adult_classes': ('Кто может заниматься?', 'Kim məşğul ola bilər?', 'Who can attend?'),
        'region': ('Город / регион', 'Şəhər / region', 'City / region'),
        'district': ('Район Баку', 'Bakı rayonu', 'Baku district'),
        'metro': ('Метро', 'Metro', 'Metro'),
        'address': ('Адрес', 'Ünvan', 'Address'),
        'phone1': ('Основной телефон', 'Əsas telefon', 'Main phone'),
        'phone2': ('Дополнительный телефон', 'Əlavə telefon', 'Additional phone'),
        'phone3': ('Ещё один телефон', 'Digər telefon', 'Another phone'),
        'website': ('Сайт', 'Veb-sayt', 'Website'),
        'lesson_duration_minutes': ('Длительность занятия, минут', 'Məşğələnin müddəti, dəqiqə', 'Lesson duration, minutes'),
        'lessons_per_week': ('Занятий в неделю', 'Həftədə məşğələ', 'Lessons per week'),
        'lessons_per_month': ('Занятий в месяц', 'Ayda məşğələ', 'Lessons per month'),
        'photo': ('Главное фото', 'Əsas şəkil', 'Main photo'),
        'gallery_images': ('Дополнительные фото (до 10)', 'Əlavə şəkillər (10-dək)', 'Gallery photos (up to 10)'),
        'moderation_note': ('Комментарий модератору', 'Moderator üçün şərh', 'Note to moderator'),
        'schedule': ('Расписание текстом', 'Mətn cədvəli', 'Text schedule'),
        'extra_conditions': ('Ранее добавленные условия', 'Əvvəl əlavə edilmiş şərtlər', 'Previously added conditions'),
        'additional_info': ('Ранее добавленная информация', 'Əvvəl əlavə edilmiş məlumat', 'Previously added information'),
    }
    for prefix, translations in {
        'name': ('Название', 'Ad', 'Name'),
        'description': ('Описание', 'Təsvir', 'Description'),
        'extra_conditions': ('Дополнительные условия', 'Əlavə şərtlər', 'Additional conditions'),
        'additional_info': ('Дополнительная информация', 'Əlavə məlumat', 'Additional information'),
    }.items():
        for lang in ('az','ru','en'):
            labels[f'{prefix}_{lang}'] = tuple(f'{label} ({lang.upper()})' for label in translations)
    for name, translations in labels.items():
        if name in form.fields:
            form.fields[name].label = t(*translations)
    form.fields['offers_adult_classes'].choices = (('0',t('Только дети','Yalnız uşaqlar','Children only')),('1',t('Дети и взрослые','Uşaqlar və böyüklər','Children and adults')))
    form.fields['lesson_format'].choices = (('', '—'),('group',t('Групповые','Qrup','Group')),('individual',t('Индивидуальные','Fərdi','Individual')))
    hints = {
        'region': ('Выберите город или регион.', 'Şəhər və ya region seçin.', 'Choose a city or region.'),
        'district': ('Обязательно для Баку.', 'Bakı üçün məcburidir.', 'Required for Baku.'),
        'metro': ('Необязательно: ближайшая станция.', 'İstəyə görə: yaxın stansiya.', 'Optional: nearest station.'),
        'address': ('Улица, дом, ориентир.', 'Küçə, bina, istiqamət.', 'Street, building, landmark.'),
        'offers_adult_classes': ('Возраст выше относится к детским группам.', 'Yuxarıdakı yaş uşaqların qruplarına aiddir.', 'The age range above describes children’s groups.'),
        'moderation_note': ('До 500 символов; посетители не увидят этот комментарий.', '500 simvoladək; ziyarətçilər bu şərhi görməyəcək.', 'Up to 500 characters; visitors will not see this note.'),
    }
    for name, field in form.fields.items():
        if name in hints:
            field.help_text = t(*hints[name])
        elif name not in ('name_az','description_az','photo','gallery_images'):
            field.help_text = ''


def ui_copy():
    return dict(

        section_nav=t('Раздел формы', 'Formanın bölməsi', 'Form section'),
        not_saved=t('Ещё не сохранено', 'Hələ saxlanılmayıb', 'Not saved yet'),
        saved_card=t('Карточка сохранена', 'Kart saxlanılıb', 'Listing saved'),
        saving_error=t('Исправьте ошибки — карточка не сохранена', 'Səhvləri düzəldin — kart saxlanılmayıb', 'Correct the errors — listing not saved'),
        needs_check=t('Ввод изменён. Готовность проверит сервер при отправке.', 'Məlumat dəyişib. Hazırlığı göndərərkən server yoxlayacaq.', 'Values changed. The server will check readiness on submission.'),
        requirements=t('Требования к отправке', 'Göndərmə tələbləri', 'Submission requirements'),
        requirements_hint=t('Эти пункты нужны для отправки. Неполный текст можно сохранить в черновике; выбранные фото сохраните отдельным явным действием.', 'Bu bəndlər göndərmək üçün lazımdır. Natamam mətni qaralamada saxlaya bilərsiniz; seçilmiş şəkilləri ayrıca açıq əməliyyatla saxlayın.', 'These items are needed to submit. Save incomplete text as a draft; save selected photos with an explicit action.'),
        contact_choice=t('Один из контактов — для отправки', 'Əlaqələrdən biri — göndərmək üçün', 'One contact — needed to submit'),
        translations_hint=t('Переводы не создаются автоматически. Если текст на выбранном языке пуст, посетитель увидит текст AZ.', 'Tərcümələr avtomatik yaradılmır. Seçilmiş dildə mətn boşdursa, ziyarətçi AZ mətnini görəcək.', 'Translations are not created automatically. When the selected language is empty, visitors see AZ text.'),
        preview_language=t('Язык предпросмотра', 'Önbaxış dili', 'Preview language'),
        preview_hint=t('Краткий предпросмотр введённых данных. Отправка ещё не публикует место.', 'Daxil edilmiş məlumatın qısa önbaxışı. Göndərmək məkanı hələ dərc etmir.', 'A short preview of your input. Submission does not publish the place.'),
        state_new=t('Новая карточка', 'Yeni kart', 'New listing'),
        state_draft=t('Черновик', 'Qaralama', 'Draft'),
        state_pending=t('На модерации', 'Moderasiyada', 'Under review'),
        state_published=t('Опубликовано', 'Dərc edilib', 'Published'),
        state_rejected=t('Отказ — исправьте и отправьте снова', 'Rədd edilib — düzəldin və yenidən göndərin', 'Rejected — correct and resubmit'),
        photo_optional=t('Фото необязательно для публикации. Выбранный файл проверяется сервером.', 'Şəkil dərc üçün məcburi deyil. Seçilmiş faylı server yoxlayır.', 'A photo is optional for publication. The server validates a selected file.'),
        saved_gallery=t('Галерея сохранённой редакции', 'Saxlanmış redaksiyanın qalereyası', 'Gallery of the saved revision'),
        saved_gallery_hint=t('Эти фото уже сохранены. Они появятся в публичной карточке после одобрения. Управление ранее добавленными фото ниже относится к основной карточке.', 'Bu şəkillər artıq saxlanıb. Təsdiqdən sonra açıq kartda görünəcək. Aşağıdakı əvvəlki şəkillərin idarə edilməsi əsas karta aiddir.', 'These photos are saved and will appear publicly after approval. The existing-photo controls below refer to the main listing.'),
        photo_recommendation=t('Квадратный кадр рекомендуется для каталога; минимум 1200×1200 не требуется.', 'Kataloq üçün kvadrat kadr tövsiyə edilir; 1200×1200 minimumu tələb edilmir.', 'A square crop is recommended for the catalog; 1200×1200 is not a minimum.'),
        photo_remove_hint=t('Фотография будет удалена после сохранения. Отсутствие фото не блокирует публикацию.', 'Şəkil saxlandıqdan sonra silinəcək. Şəklin olmaması dərcə mane olmur.', 'The photo will be removed after saving. Its absence does not block publication.'),
        errors_title=t('Исправьте ошибки', 'Səhvləri düzəldin', 'Correct the errors'),
        section_about=t('О месте', 'Məkan haqqında', 'About the place'),
        section_contact=t('Адрес и контакты', 'Ünvan və əlaqə', 'Address and contact'),
        section_offer=t('Занятия и цены', 'Məşğələlər və qiymətlər', 'Activities and prices'),
        section_review=t('Фото и проверка', 'Şəkillər və yoxlama', 'Photos and review'),
        standalone=t('Место может быть без организации. Связать его можно позже в кабинете.', 'Məkan təşkilatsız ola bilər. Onu daha sonra kabinetdə əlaqələndirə bilərsiniz.', 'A place can stand alone. Link it to an organization later in your workspace.'),
        public_space=t('Общественное место', 'İctimai məkan', 'Public place'),
        business=t('Бизнес', 'Biznes', 'Business'),
        common_ticket=t('Общий билет или вход', 'Ümumi bilet və ya giriş', 'General admission or ticket'),
        shared_program=t('Общая программа', 'Ümumi proqram', 'Shared program'),
        local_activity=t('Местное занятие', 'Yerli məşğələ', 'Local activity'),
        category=t('Категория занятия', 'Məşğələ kateqoriyası', 'Activity category'),
        subcategory=t('Подкатегория занятия', 'Məşğələ alt kateqoriyası', 'Activity subcategory'),
        copy_place_taxonomy=t('Скопировать категорию места', 'Məkan kateqoriyasını köçür', 'Copy Place category'),
        taxonomy_reset=t('Подкатегория не подходит новой категории и сброшена.', 'Alt kateqoriya yeni kateqoriyaya uyğun deyil və silindi.', 'The subcategory did not match the new category and was cleared.'),
        structure_conflict=t('Права или структура места изменились. Ваш ввод остался на экране. Обновите страницу перед сохранением.', 'Hüquqlar və ya məkanın strukturu dəyişib. Daxil etdikləriniz ekranda qalıb. Saxlamazdan əvvəl səhifəni yeniləyin.', 'Access or Place structure changed. Your input is still here. Reload before saving.'),
        local_supplement=t('Местное дополнение (AZ)', 'Yerli əlavə (AZ)', 'Local supplement (AZ)'),
        group_teachers=t('Преподаватели', 'Müəllimlər', 'Teachers'),
        group_conditions=t('Условия группы (AZ)', 'Qrup şərtləri (AZ)', 'Group conditions (AZ)'),
        activity_explain=t('Для парка или общего входного билета занятие добавлять не нужно.', 'Park və ya ümumi giriş bileti üçün məşğələ əlavə etmək lazım deyil.', 'A park or general admission does not need an activity.'),
        live_version=t('Опубликованная версия', 'Dərc edilmiş versiya', 'Live version'),
        candidate_version=t('Новая редакция', 'Yeni redaksiya', 'New edit'),
        candidate_help=t('Черновик и изменения на проверке не скрывают опубликованное место.', 'Qaralama və yoxlamadakı dəyişikliklər dərc edilmiş məkanı gizlətmir.', 'Drafts and pending edits do not hide the live place.'),
        server_saving=t('Сохраняем на сервере…', 'Serverdə saxlanılır…', 'Saving to server…'),
        server_saved=t('Текст и тарифы сохранены на сервере', 'Mətn və tariflər serverdə saxlanılıb', 'Text and plans saved to server'),
        server_conflict=t('Другой редактор изменил черновик. Ваш ввод сохранён в этой вкладке; сохранение остановлено. Откройте актуальную версию отдельно и сравните изменения.', 'Başqa redaktor qaralamanı dəyişib. Daxil etdikləriniz bu səhifədə saxlanıb; saxlama dayandırılıb. Cari versiyanı ayrıca açıb dəyişiklikləri müqayisə edin.', 'Another editor changed the draft. Your input remains in this tab; saving is paused. Open the current version separately to compare changes.'),
        open_current_draft=t('Открыть актуальную версию в новой вкладке', 'Cari versiyanı yeni səhifədə açın', 'Open the current version in a new tab'),
        state_changes=t('Нужны исправления', 'Düzəlişlər lazımdır', 'Changes requested'),
        upload_pending=t('Фото ещё не загружено. Оно сохранится после явного действия.', 'Şəkil hələ yüklənməyib. Açıq əməliyyatdan sonra saxlanılacaq.', 'Photo is not uploaded yet. It will be saved after an explicit action.'),
        review_summary=t('Проверка публикации выполняется сервером при отправке.', 'Dərc yoxlaması göndərmə zamanı serverdə aparılır.', 'The server checks publication requirements when you submit.'),
        optional_map=t('Точка на карте необязательна; адрес можно указать без неё.', 'Xəritədə nöqtə məcburi deyil; ünvanı onsuz da göstərə bilərsiniz.', 'The map pin is optional; you can provide the address without it.'),
        inherited_contact=t('Контакт берётся из подтверждённой организации.', 'Əlaqə təsdiqlənmiş təşkilatdan götürülür.', 'Contact comes from the confirmed organization.'),
        local_contact=t('Местный контакт', 'Yerli əlaqə', 'Local contact'),
        title=t('Постоянное место', 'Daimi məkan', 'Permanent place'),
        intro=t('Расскажите о месте. После проверки оно появится в каталоге.', 'Məkan haqqında məlumat verin. Yoxlamadan sonra kataloqda görünəcək.', 'Tell us about the place. It will appear in the catalog after review.'),
        back=t('Назад', 'Geri', 'Back'), next=t('Дальше', 'Davam et', 'Continue'),
        draft=t('Сохранить черновик', 'Qaralamanı saxla', 'Save draft'),
        apply_changes=t('Применить изменения', 'Dəyişiklikləri tətbiq et', 'Apply changes'),
        submit=t('Отправить на модерацию', 'Moderasiyaya göndər', 'Send for review'),
        places=t('Мои места', 'Məkanlarım', 'My places'),
        progress=t('Ваше место — шаг за шагом', 'Məkanınız — addım-addım', 'Your place, step by step'),
        step=t('Шаг', 'Addım', 'Step'),
        of=t('из', '/', 'of'),
        photo_choose=t('Выберите фотографию', 'Şəkil seçin', 'Choose a photo'),
        photo_drop=t('Перетащите сюда или нажмите для выбора', 'Buraya sürükləyin və ya seçmək üçün basın', 'Drop here or click to choose'),
        saved_later=t('Можно продолжить позже: сохраните черновик.', 'Daha sonra davam etmək üçün qaralamanı saxlayın.', 'Save a draft to continue later.'),
        optional=t('Дополнительно', 'Əlavə məlumat', 'Additional details'),
        required=t('Обязательно для отправки', 'Göndərmək üçün məcburidir', 'Required for submission'),
        required_badge=t('Обязательно', 'Məcburi', 'Required'),
        optional_badge=t('Необязательно', 'Məcburi deyil', 'Optional'),
        one_name=t('На одном языке', 'Bir dildə', 'In one language'),
        name_requirement=t('Название на азербайджанском', 'Azərbaycan dilində ad', 'Name in Azerbaijani'),
        point_requirement=t('Точка на карте', 'Xəritədə nöqtə', 'Map point'),
        price_requirement=t('Основной тариф', 'Əsas tarif', 'Primary plan'),
        schedule_requirement=t('Дни и часы или текст расписания', 'Gün və saatlar və ya mətn cədvəli', 'Opening hours or text schedule'),
        fields_ready=t('Готово', 'Hazırdır', 'Ready'),
        fields_remaining=t('Осталось', 'Qalıb', 'Remaining'),
        draft_hint=t('Для черновика можно заполнить позже. Дополнительные поля отмечены отдельно.', 'Qaralama üçün sonra doldura bilərsiniz. Əlavə sahələr ayrıca işarələnib.', 'You can complete these later in a draft. Optional fields are marked separately.'),
        translations=t('Другие языки · RU / EN', 'Digər dillər · RU / EN', 'Other languages · RU / EN'),
        range=t('Диапазон возраста', 'Yaş aralığı', 'Age range'),
        open_age=t('От указанного возраста', 'Göstərilən yaşdan', 'From this age'),
        all_ages=t('Все возрасты · 0+', 'Bütün yaşlar · 0+', 'All ages · 0+'),
        add_plan=t('Добавить тариф', 'Tarif əlavə et', 'Add a plan'),
        add_activity=t('Добавить занятие', 'Məşğələ əlavə et', 'Add an activity'),
        activity_name=t('Название занятия (AZ)', 'Məşğələnin adı (AZ)', 'Activity name (AZ)'),
        activity_description=t('Описание занятия (AZ)', 'Məşğələnin təsviri (AZ)', 'Activity description (AZ)'),
        add_group=t('Добавить группу', 'Qrup əlavə et', 'Add a group'),
        group_name=t('Название группы (AZ)', 'Qrupun adı (AZ)', 'Group name (AZ)'),
        group_age_from=t('Возраст от', 'Yaşdan', 'Age from'),
        group_age_to=t('Возраст до', 'Yaşa qədər', 'Age to'),
        group_language=t('Язык занятия', 'Məşğələ dili', 'Teaching language'),
        group_schedule=t('Расписание группы', 'Qrup cədvəli', 'Group schedule'),
        plan_title=t('Название тарифа (AZ)', 'Tarif adı (AZ)', 'Plan title (AZ)'),
        plan_type=t('Тип тарифа', 'Tarif növü', 'Plan type'),
        plan_price_kind=t('Тип цены', 'Qiymət növü', 'Price kind'),
        plan_price=t('Цена', 'Qiymət', 'Price'),
        plan_price_min=t('Цена от', 'Başlanğıc qiymət', 'Price from'),
        plan_price_max=t('Цена до', 'Son qiymət', 'Price to'),
        plan_interval=t('Период оплаты', 'Ödəniş dövrü', 'Billing period'),
        plan_advanced=t('Условия тарифа', 'Tarif şərtləri', 'Plan terms'),
        group_format=t('Формат группы', 'Qrup formatı', 'Group format'),
        plan_count=t('тарифов', 'tarif', 'plans'),
        plan_count_one=t('тариф', 'tarif', 'plan'),
        plan_count_few=t('тарифа', 'tarif', 'plans'),
        activity_count=t('занятий', 'məşğələ', 'activities'),
        activity_count_one=t('занятие', 'məşğələ', 'activity'),
        activity_count_few=t('занятия', 'məşğələ', 'activities'),
        group_count=t('групп', 'qrup', 'groups'),
        group_count_one=t('группа', 'qrup', 'group'),
        group_count_few=t('группы', 'qrup', 'groups'),
        plan_currency=t('Валюта', 'Valyuta', 'Currency'),
        plan_role=t('Роль тарифа', 'Tarifin rolu', 'Plan role'),
        plan_billing=t('Оплата', 'Ödəniş', 'Billing'),
        plan_trial=t('Пробный', 'Sınaq', 'Trial'),
        plan_required=t('Обязательная доплата', 'Məcburi əlavə ödəniş', 'Required fee'),
        remove_activity=t('Удалить занятие', 'Məşğələni sil', 'Remove activity'),
        remove_group=t('Удалить группу', 'Qrupu sil', 'Remove group'),
        remove_plan=t('Удалить тариф', 'Tarifi sil', 'Remove plan'),
        plans_hint=t('До 12 тарифов. Доплаты и депозит указываются отдельно от основной цены.', '12-dək tarif. Əlavə ödəniş və depozit əsas qiymətdən ayrıdır.', 'Up to 12 plans. Add-ons and deposits are separate from the primary price.'),
        manual=t('Ввести координаты вручную', 'Koordinatları əl ilə daxil et', 'Enter coordinates manually'),
        map_hint=t('Точка необязательна. Если указали координаты, проверьте их точность.', 'Nöqtə məcburi deyil. Koordinat daxil etmisinizsə, dəqiqliyini yoxlayın.', 'The pin is optional. If you enter coordinates, check their accuracy.'),
        map_changed=t('Адрес изменился. Проверьте точку на карте.', 'Ünvan dəyişdi. Xəritədə nöqtəni yoxlayın.', 'The address changed. Check the map point.'),
        map_confirm=t('Точка верна', 'Nöqtə düzgündür', 'Point is correct'),
        map_unavailable=t('Карта недоступна. Можно ввести координаты вручную.', 'Xəritə əlçatan deyil. Koordinatları əl ilə daxil edə bilərsiniz.', 'Map unavailable. You can enter coordinates manually.'),
        remove=t('Удалить при сохранении', 'Saxlayarkən sil', 'Remove when saving'),
        restore=t('Отменить удаление', 'Silməni ləğv et', 'Undo removal'),
        photos_hint=t('Главное фото и до 10 дополнительных. Новые фото можно добавлять частями.', 'Əsas şəkil və 10-dək əlavə şəkil. Şəkilləri hissə-hissə əlavə edə bilərsiniz.', 'One main photo and up to 10 gallery photos. Add photos in multiple batches.'),
        preview=t('Так увидят ваше место', 'Məkanınız belə görünəcək', 'Your place preview'),
        check=t('Проверьте перед отправкой', 'Göndərməzdən əvvəl yoxlayın', 'Review before submitting'),
        empty=t('Не заполнено', 'Doldurulmayıb', 'Not filled in'),
        ready=t('Можно отправлять на модерацию', 'Moderasiyaya göndərmək olar', 'Ready to send for review'),
        missing=t('Проверьте обязательные поля', 'Məcburi sahələri yoxlayın', 'Check required fields'),
        invalid=t('Проверьте значение', 'Dəyəri yoxlayın', 'Check this value'),
        age_range_invalid=t('Возраст «до» должен быть не меньше «от» (0–18).', 'Maksimum yaş minimum yaşdan az ola bilməz (0–18).', 'Maximum age must be greater than or equal to minimum age (0–18).'),
        age_invalid=t('Укажите возраст от 0 до 18.', '0-dan 18-dək yaş daxil edin.', 'Enter an age between 0 and 18.'),
        phone_invalid=t('Укажите корректный номер телефона (без букв).', 'Düzgün telefon nömrəsi daxil edin (hərfsiz).', 'Enter a valid phone number (no letters).'),
        url_invalid=t('Укажите корректный адрес сайта. Пример: https://site.com', 'Düzgün veb-sayt ünvanı daxil edin. Məsələn: https://sayt.com', 'Enter a valid website URL. Example: https://site.com'),
        number_invalid=t('Укажите целое положительное число.', 'Müsbət tam ədəd daxil edin.', 'Enter a positive whole number.'),
        browser_saved=t('Текст и тарифы сохранены в этом браузере. Для сохранения фото нажмите «Сохранить черновик».', 'Mətn və tariflər bu brauzerdə saxlanılıb. Şəkillər üçün «Qaralamanı saxla» düyməsini basın.', 'Text and plans saved in this browser. Use Save draft to save photos.'),
        restored=t('Черновик восстановлен. Незагруженные фотографии выберите заново.', 'Qaralama bərpa edildi. Yüklənməmiş şəkilləri yenidən seçin.', 'Draft restored. Select any unuploaded photos again.'),
        save_failed=t('Не удалось сохранить. Данные остались в форме; попробуйте ещё раз.', 'Yadda saxlamaq mümkün olmadı. Məlumatlar formadadır; yenidən cəhd edin.', 'Could not save. Your data remains in the form; please try again.'),
        storage_error=t('Браузер не смог сохранить черновик. Сохраните его кнопкой ниже.', 'Brauzer qaralamanı saxlaya bilmədi. Aşağıdakı düymə ilə saxlayın.', 'Browser draft could not be saved. Use the Save draft button.'),
        offline=t('Нет соединения. Текст остаётся в этом браузере; отправка будет доступна после подключения.', 'Bağlantı yoxdur. Mətn bu brauzerdə qalır; göndərmək üçün internetə qoşulun.', 'Offline. Text stays in this browser; reconnect to submit.'),
        unsaved=t('Есть несохранённые изменения.', 'Saxlanmamış dəyişikliklər var.', 'You have unsaved changes.'),
        request=t('По запросу', 'Sorğu ilə', 'On request'), free=t('Бесплатно', 'Pulsuz', 'Free'),
        from_price=t('От', 'Başlayır', 'From'),
        pending=t('Карточка появится после одобрения модератором.', 'Kart moderator təsdiqindən sonra görünəcək.', 'The card becomes public after moderator approval.'),
        deletion=t('Удалить место', 'Məkanı sil', 'Delete place'),
        delete_confirm=t('Удалить карточку места?', 'Məkan kartı silinsin?', 'Delete this place?'),
        field_error=t('Исправьте поле', 'Sahəni düzəldin', 'Correct this field'),
        change_mode=t('При смене типа цены или оплаты несовместимые суммы и периоды очищаются.', 'Qiymət və ya ödəniş növü dəyişəndə uyğun olmayan məbləğ və dövrlər təmizlənir.', 'Changing the price or billing type clears incompatible amounts and periods.'),
        select_subcategory=t('Выберите подкатегорию', 'Alt kateqoriya seçin', 'Select subcategory'),
        select_category_first=t('Сначала выберите категорию', 'Əvvəlcə kateqoriyanı seçin', 'Select a category first'),
        no_subcategories=t('Для этой категории нет подкатегорий', 'Bu kateqoriya üçün alt kateqoriya yoxdur', 'No subcategories for this category'),
        search_subcategory=t('Поиск подкатегории...', 'Alt kateqoriya axtarışı...', 'Search subcategories...'),
        options_count=t('вариантов', 'variant', 'options'),
        clear_selection=t('Очистить выбор', 'Seçimi təmizlə', 'Clear selection'),
        leave_modal_title=t('Есть несохранённые данные', 'Yadda saxlanılmamış məlumatlar var', 'You have unsaved changes'),
        leave_modal_desc_lang=t('Вы переключаете язык страницы. Чтобы не потерять введённые данные, сохраните черновик — заполнение продолжится на выбранном языке.', 'Siz səhifənin dilini dəyişirsiniz. Daxil etdiyiniz məlumatların itməməsi üçün qaralamanı saxlayın — məlumatlar seçdiyiniz dildə davam edəcək.', 'You are switching the language. Save your draft so you can continue in the selected language without losing any data.'),
        leave_modal_desc_nav=t('Вы переходите на другую страницу. Чтобы не потерять введённые данные, сохраните черновик — вы сможете продолжить в любое время.', 'Siz başqa səhifəyə keçirsiniz. Daxil etdiyiniz məlumatların itməməsi üçün qaralamanı saxlayın — istənilən vaxt davam edə bilərsiniz.', 'You are navigating away. Save your draft so you can continue at any time without losing your progress.'),
        leave_modal_save=t('Сохранить черновик и перейти', 'Qaralamanı saxla və davam et', 'Save draft and proceed'),
        leave_modal_stay=t('Остаться и продолжить', 'Doldurmağa davam et', 'Keep editing'),
        leave_modal_discard=t('Не сохранять', 'Yadda saxlamadan çıx', 'Discard changes'),
        draft_saved_toast=t('Черновик успешно сохранён', 'Qaralama uğurla yadda saxlanıldı', 'Draft successfully saved'),
    )



def build_steps(form):
    def fields(names):
        return [form[name] for name in names.split() if name in form.fields]
    def step(number, title, hint, names='', optional=''):
        return dict(number=number, title=title, hint=hint, fields=fields(names), optional=fields(optional))
    return [
        step(1, t('О месте', 'Məkan haqqında', 'About the place'), t('Начните с названия, категории и описания.', 'Ad, kateqoriya və təsvirlə başlayın.', 'Start with a name, category and description.'), 'name_az description_az nature category subcategory', 'name_ru description_ru name_en description_en'),
        step(2, t('Для кого', 'Kimlər üçün', 'Audience'), t('Возраст относится к детским группам.', 'Yaş uşaqların qruplarına aiddir.', 'The age range describes children’s groups.'), 'age_from age_to offers_adult_classes', 'lesson_duration_minutes lesson_format lessons_per_week lessons_per_month'),
        step(3, t('Тарифы', 'Tariflər', 'Pricing'), t('Что входит и сколько стоит.', 'Nələr daxildir və qiyməti nədir.', 'What is included and what it costs.')),
        step(4, t('Адрес и карта', 'Ünvan və xəritə', 'Address and map'), t('Помогите семьям найти вход.', 'Ailələrə girişi tapmağa kömək edin.', 'Help families find the entrance.'), 'region district address', 'metro'),
        step(5, t('Контакты и расписание', 'Əlaqə və cədvəl', 'Contact and schedule'), t('Как связаться и когда можно прийти.', 'Necə əlaqə saxlamaq və nə vaxt gəlmək olar.', 'How to get in touch and when to visit.'), 'phone1', 'phone2 phone3 instagram website extra_conditions_az extra_conditions_ru extra_conditions_en additional_info_az additional_info_ru additional_info_en extra_conditions additional_info'),
        step(6, t('Фотографии', 'Şəkillər', 'Photos'), t('Покажите само место и занятия.', 'Məkanı və məşğələləri göstərin.', 'Show the place and its activities.'), 'photo gallery_images'),
        step(7, t('Проверка', 'Yoxlama', 'Review'), t('Проверьте все разделы и отправьте на модерацию.', 'Bütün bölmələri yoxlayıb moderasiyaya göndərin.', 'Review every section and send for moderation.'), 'moderation_note'),
    ]


def continuous_sections(form):
    """Four owner sections; legacy volunteer steps remain untouched."""
    steps = build_steps(form)
    titles = ui_copy()
    return [
        dict(number=1, title=titles['section_about'], parts=[steps[0]]),
        dict(number=2, title=titles['section_contact'], parts=[steps[3], steps[4]]),
        dict(number=3, title=titles['section_offer'], parts=[steps[1], steps[2]]),
        dict(number=4, title=titles['section_review'], parts=[steps[5], steps[6]]),
    ]
