const {test}=require('node:test'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
for(const kind of ['pageswap','pagereveal'])for(const rejected of [true,false])test(`${kind}: ${rejected?'aborted':'completed'} transition cleans cover without unhandled rejection`,()=>{
 const code=`const {JSDOM}=require('jsdom'),fs=require('node:fs');const dom=new JSDOM('<div class="card"><a href="/en/place/1-synthetic/"><img class="card-media-img"></a></div><img class="place-gallery__image">',{url:'http://localhost/en/place/1-synthetic/',runScripts:'outside-only'});const w=dom.window;w.matchMedia=()=>({matches:false});let errors=0;process.on('unhandledRejection',()=>errors++);w.eval(fs.readFileSync('static/js/motion.js','utf8'));w.document.querySelector('a').dispatchEvent(new w.MouseEvent('click',{bubbles:true}));const e=new w.Event('${kind}');e.activation={entry:{url:'http://localhost/en/place/1-synthetic/'}};e.viewTransition={skipTransition:()=>{},ready:Promise.resolve(),finished:Promise.resolve(),${kind==='pageswap'?'finished':'ready'}:${rejected?"Promise.reject(new Error('Transition aborted'))":"Promise.resolve()"}};w.dispatchEvent(e);setTimeout(()=>{console.log(JSON.stringify({errors,names:[...w.document.querySelectorAll('img')].map(e=>e.style.viewTransitionName)}));w.close();},20);`;
 const r=spawnSync(process.execPath,['-e',code],{encoding:'utf8',env:process.env});assert.equal(r.status,0,r.stderr);const data=JSON.parse(r.stdout.trim());assert.equal(data.errors,0);assert.ok(data.names.every(n=>!n));
});
for(const kind of ['pageswap','pagereveal'])test(`${kind}: opt-out navigation handles rejected ready outside public place routes`,()=>{
 const code=`const {JSDOM}=require('jsdom'),fs=require('node:fs');const dom=new JSDOM('<p>Workspace</p>',{url:'http://localhost/en/account/organizations/',runScripts:'outside-only'});const w=dom.window;w.matchMedia=()=>({matches:false});let errors=0;process.on('unhandledRejection',()=>errors++);w.eval(fs.readFileSync('static/js/motion.js','utf8'));const e=new w.Event('${kind}');e.activation={entry:{url:'http://localhost/en/account/places/'}};e.viewTransition={skipTransition:()=>{},ready:Promise.reject(new Error('ViewTransition opt-in disabled')),finished:Promise.resolve()};w.dispatchEvent(e);setTimeout(()=>{console.log(JSON.stringify({errors}));w.close();},20);`;
 const r=spawnSync(process.execPath,['-e',code],{encoding:'utf8',env:process.env});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout.trim()).errors,0);
});
test('outgoing account navigation skips transition; public place navigation remains enabled',()=>{
 const {JSDOM}=require('jsdom'),fs=require('node:fs');const dom=new JSDOM('<p>Public catalog</p>',{url:'http://localhost/en/places/',runScripts:'outside-only'});const w=dom.window;w.matchMedia=()=>({matches:false});w.eval(fs.readFileSync('static/js/motion.js','utf8'));for(const path of ['/ru/account/places/','/account/organizations/69/requests/120/recovery/','/en/account/organizations/','/en/place/1-test/']){let skipped=0;const e=new w.Event('pageswap');e.activation={entry:{url:'http://localhost'+path}};e.viewTransition={skipTransition:()=>{},ready:Promise.resolve(),finished:Promise.resolve(),skipTransition:()=>skipped++};w.dispatchEvent(e);assert.equal(skipped,path.includes('/account/')?1:0);}w.close();
});
