"""Full suite in the new immutable image; only one verified QA document is added."""
import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import uuid

parser=argparse.ArgumentParser()
parser.add_argument('--stamp',required=True)
args=parser.parse_args()
assert re.fullmatch(r'[a-z0-9-]+',args.stamp)
source=Path('/mnt/c/kidsmap')
metadata=json.loads((source/'docs/task33/completion/artifact.json').read_text())
image=metadata['image_id'];root=Path(metadata['standby']);here=root/'docs/task33/qa04'
output=Path('/tmp/task33-completion-image-'+args.stamp)
retained=Path('/root/task33-evidence/completion-image-'+args.stamp)
assert not output.exists() and not retained.exists()
qa=metadata['qa_document'];document=Path(qa['path'])
assert document.is_file() and not document.is_symlink()
assert hashlib.sha256(document.read_bytes()).hexdigest()==qa['sha256']
assert hashlib.sha256((source/qa['relative_path']).read_bytes()).hexdigest()==qa['sha256']
manifest=json.loads((Path(metadata['archive']).parent/'manifest.json').read_text())
safe_env={'PATH':'/usr/bin:/bin','LANG':'C.UTF-8'}
# Hash every Python/template/asset source in the image against the frozen archive.
# Translation .mo files may be regenerated by Dockerfile; source .po is compared.
expected={row['path']:row['sha256'] for row in manifest['files'] if not row['path'].endswith('.mo')}
code="import hashlib,json;from pathlib import Path;paths=json.loads(input());print(json.dumps({p:hashlib.sha256((Path('/app')/p).read_bytes()).hexdigest() for p in paths}))"
probe=subprocess.run(['docker','run','--rm','--interactive','--pull=never','--network','none','--read-only',
    '--cap-drop=ALL','--security-opt=no-new-privileges','--entrypoint','/usr/local/bin/python',image,'-c',code],
    input=json.dumps(list(expected)),capture_output=True,text=True,env=safe_env,check=True)
assert json.loads(probe.stdout)==expected,'Frozen image source differs'
venv=root/'.venv'
if not venv.exists():venv.symlink_to('/root/kidsmap-task33/.venv',target_is_directory=True)
spec=importlib.util.spec_from_file_location('qa04_image',here/'run.py')
base=importlib.util.module_from_spec(spec);spec.loader.exec_module(base)
original_popen=subprocess.Popen
nonce=uuid.uuid4().hex;name='kidsmap-completion-image-'+nonce[:12]
launched=[]

def dispatch(command,*pos,**kw):
    if not (isinstance(command,list) and len(command)==5 and command[1]=='-c' and 'commands.main' in command[2]):
        return original_popen(command,*pos,**kw)
    assert command[3]=='all' and json.loads(command[4])==[]
    env=dict(kw.pop('env'));kw.pop('cwd')
    run=Path(env['TASK33_QA_ROOT']).resolve(strict=True)
    sock=Path(env['TASK33_QA_SOCKET']).resolve(strict=True)
    out=Path(env['TASK33_QA_OUTPUT']).resolve(strict=True)
    assert run.parent==Path('/tmp') and run.name.startswith('kidsmap-task33-qa04-')
    assert sock.is_relative_to(root/'.tmp') and out==output
    image_socket=Path('/app/.tmp')/sock.parent.name/'socket'
    env.update(PATH='/usr/local/bin:/usr/bin:/bin',PYTHONPATH='/app/docs/task33/qa04:/app/src',TASK33_QA_SOCKET=str(image_socket))
    cmd=['docker','run','--rm','--pull=never','--name',name,'--label','kidsmap.completion.owner='+nonce,
        '--network','none','--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--workdir','/app',
        '--mount',f'type=bind,src={run},dst={run}',
        '--mount',f'type=bind,src={sock.parent},dst={image_socket.parent}',
        '--tmpfs','/tmp:rw,noexec,nosuid,size=256m',
        '--mount',f'type=bind,src={out},dst={out}',
        '--mount',f'type=bind,src={document},dst=/app/{qa["relative_path"]},readonly']
    for key,value in sorted(env.items()):cmd.extend(['--env',key+'='+value])
    child="import sys,json;sys.path.insert(0,'/app/src');import commands;sys.exit(commands.main(sys.argv[1],json.loads(sys.argv[2])))"
    cmd.extend(['--entrypoint','/usr/local/bin/python',image,'-c',child,command[3],command[4]])
    launched.append(True)
    return original_popen(cmd,*pos,env=safe_env,**kw)

subprocess.Popen=dispatch
try:
    sys.argv=[str(here/'run.py'),'--mode','all','--output',str(output)]
    result=base.main()
finally:
    subprocess.Popen=original_popen
    check=subprocess.run(['docker','inspect',name],capture_output=True,env=safe_env)
    assert check.returncode!=0,'Owned image container retained'
    report={'image_id':image,'image_source_count':len(expected),'image_source_match':True,
        'qa_document':qa,'only_document_mounted_readonly':True,'application_code_mount':False,
        'network':'none','read_only':True,'capabilities_dropped':True,'child_launched':bool(launched),
        'socket_contract':'/app/.tmp/kidsmap-task33-qa04-socket-*/socket',
        'writable_tmpfs':'/tmp rw,noexec,nosuid,size=256m',
        'child_removed':True,'production':'NOT_CONTACTED'}
    (output/'image-runtime.json').write_text(json.dumps(report,indent=2)+'\n')
    shutil.copytree(output,retained)
print(json.dumps({'evidence':str(retained),'exit':result,'image_id':image}))
raise SystemExit(result)
