from __future__ import annotations

import json
from collections import defaultdict, deque
from datetime import timedelta
from pathlib import Path

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError
from django.core.management.color import no_style
from django.db import connections, transaction
from django.utils import timezone


EXCLUDED_TABLES = {
    "django_session",
    "catalog_sitevisit",
    # These are generated by migrate. Their IDs are checked before copying
    # permission relations, but the generated rows themselves are not replaced.
    "django_content_type",
    "auth_permission",
}


def managed_models_by_table():
    result = {}
    for model in apps.get_models(include_auto_created=True):
        opts = model._meta
        if opts.managed and not opts.proxy:
            result.setdefault(opts.db_table, model)
    return result


def ordered_models(models_by_table):
    dependencies = defaultdict(set)
    dependents = defaultdict(set)
    tables = set(models_by_table)
    for table, model in models_by_table.items():
        for field in model._meta.concrete_fields:
            related = getattr(field.remote_field, "model", None)
            related_table = getattr(getattr(related, "_meta", None), "db_table", None)
            if related_table in tables and related_table != table:
                dependencies[table].add(related_table)
                dependents[related_table].add(table)

    ready = deque(sorted(tables - set(dependencies)))
    ordered = []
    while ready:
        table = ready.popleft()
        ordered.append(models_by_table[table])
        for dependent in sorted(dependents[table]):
            dependencies[dependent].discard(table)
            if not dependencies[dependent]:
                ready.append(dependent)

    remaining = tables - {model._meta.db_table for model in ordered}
    ordered.extend(models_by_table[table] for table in sorted(remaining))
    return ordered


def table_columns(connection, table):
    with connection.cursor() as cursor:
        return {
            column.name
            for column in connection.introspection.get_table_description(cursor, table)
        }


class Command(BaseCommand):
    help = "Idempotently copy legacy MariaDB business data into a migrated PostgreSQL database."

    def add_arguments(self, parser):
        parser.add_argument("--source", default="legacy")
        parser.add_argument("--target", default="default")
        parser.add_argument("--batch-size", type=int, default=1000)
        parser.add_argument("--analytics-days", type=int, default=180)
        parser.add_argument("--report", default="migration-report.json")
        parser.add_argument("--dry-run", action="store_true")

    def handle(self, *args, **options):
        source_alias = options["source"]
        target_alias = options["target"]
        if source_alias == target_alias:
            raise CommandError("Source and target database aliases must be different.")
        if options["batch_size"] < 1:
            raise CommandError("--batch-size must be at least 1.")

        try:
            source = connections[source_alias]
            target = connections[target_alias]
        except KeyError as exc:
            raise CommandError(f"Unknown database alias: {exc.args[0]}") from exc
        if source.vendor != "mysql":
            raise CommandError(f"Source must be MariaDB/MySQL, got {source.vendor}.")
        if target.vendor != "postgresql":
            raise CommandError(f"Target must be PostgreSQL, got {target.vendor}.")

        source_tables = set(source.introspection.table_names())
        target_tables = set(target.introspection.table_names())
        self._verify_generated_ids(source, target, source_tables, target_tables)

        all_models = managed_models_by_table()
        copy_models = {
            table: model
            for table, model in all_models.items()
            if table in source_tables and table in target_tables and table not in EXCLUDED_TABLES
        }
        missing_business_tables = sorted(
            table for table in all_models if table not in EXCLUDED_TABLES and table not in source_tables
        )
        cutoff = timezone.now() - timedelta(days=options["analytics_days"])
        report = {
            "source": source_alias,
            "target": target_alias,
            "dry_run": options["dry_run"],
            "analytics_cutoff": cutoff.isoformat(),
            "excluded_tables": sorted(EXCLUDED_TABLES),
            "missing_source_tables": missing_business_tables,
            "tables": {},
            "errors": [],
        }

        try:
            for model in ordered_models(copy_models):
                table = model._meta.db_table
                result = self._copy_table(
                    source,
                    target,
                    model,
                    options["batch_size"],
                    cutoff,
                    options["dry_run"],
                )
                report["tables"][table] = result
                self.stdout.write(
                    f"{table}: selected={result['selected']} written={result['written']}"
                )
            if not options["dry_run"]:
                self._reset_sequences(target, copy_models.values())
        except Exception as exc:
            report["errors"].append({"type": type(exc).__name__, "message": str(exc)})
            self._write_report(options["report"], report)
            raise

        self._write_report(options["report"], report)
        self.stdout.write(self.style.SUCCESS(f"Migration report: {options['report']}"))

    def _copy_table(self, source, target, model, batch_size, cutoff, dry_run):
        table = model._meta.db_table
        source_columns = table_columns(source, table)
        target_columns = table_columns(target, table)
        fields_by_column = {
            field.column: field for field in model._meta.concrete_fields if field.column
        }
        pk_column = model._meta.pk.column
        if pk_column not in source_columns or pk_column not in target_columns:
            raise CommandError(f"{table}: primary-key column {pk_column!r} is missing.")

        selected_columns = [
            field.column
            for field in model._meta.concrete_fields
            if field.column in source_columns and field.column in target_columns
        ]
        missing_columns = [
            field.column
            for field in model._meta.concrete_fields
            if field.column in target_columns and field.column not in source_columns
        ]
        supplied_defaults = {}
        for column in missing_columns:
            field = fields_by_column[column]
            if field.has_default():
                supplied_defaults[column] = field.get_default()
            elif field.null:
                supplied_defaults[column] = None
            else:
                raise CommandError(
                    f"{table}: legacy schema lacks required target column {column!r}."
                )

        write_columns = selected_columns + list(supplied_defaults)
        source_quote = source.ops.quote_name
        target_quote = target.ops.quote_name
        where_sql = ""
        params = []
        if table == "catalog_funnelevent" and "created_at" in source_columns:
            where_sql = f" WHERE {source_quote('created_at')} >= %s"
            params.append(cutoff)
        select_sql = (
            f"SELECT {', '.join(source_quote(column) for column in selected_columns)} "
            f"FROM {source_quote(table)}{where_sql} ORDER BY {source_quote(pk_column)}"
        )
        placeholders = ", ".join(["%s"] * len(write_columns))
        update_columns = [column for column in write_columns if column != pk_column]
        if update_columns:
            conflict_sql = " DO UPDATE SET " + ", ".join(
                f"{target_quote(column)} = EXCLUDED.{target_quote(column)}"
                for column in update_columns
            )
        else:
            conflict_sql = " DO NOTHING"
        insert_sql = (
            f"INSERT INTO {target_quote(table)} "
            f"({', '.join(target_quote(column) for column in write_columns)}) "
            f"VALUES ({placeholders}) ON CONFLICT ({target_quote(pk_column)}){conflict_sql}"
        )

        selected = written = 0
        with source.cursor() as source_cursor:
            source_cursor.execute(select_sql, params)
            with transaction.atomic(using=target.alias):
                with target.constraint_checks_disabled():
                    while True:
                        rows = source_cursor.fetchmany(batch_size)
                        if not rows:
                            break
                        selected += len(rows)
                        prepared_rows = []
                        for row in rows:
                            values = dict(zip(selected_columns, row))
                            values.update(supplied_defaults)
                            prepared_rows.append(
                                tuple(
                                    fields_by_column[column].get_db_prep_save(
                                        values[column], connection=target
                                    )
                                    for column in write_columns
                                )
                            )
                        if not dry_run:
                            with target.cursor() as target_cursor:
                                target_cursor.executemany(insert_sql, prepared_rows)
                            written += len(prepared_rows)
        return {
            "selected": selected,
            "written": written,
            "source_columns": selected_columns,
            "target_defaults": sorted(supplied_defaults),
        }

    def _verify_generated_ids(self, source, target, source_tables, target_tables):
        checks = {
            "django_content_type": ("app_label", "model"),
            "auth_permission": ("content_type_id", "codename"),
        }
        for table, natural_columns in checks.items():
            if table not in source_tables or table not in target_tables:
                raise CommandError(f"Required generated table is missing: {table}")
            columns = ("id", *natural_columns)
            snapshots = []
            for connection in (source, target):
                quote = connection.ops.quote_name
                sql = (
                    f"SELECT {', '.join(quote(column) for column in columns)} "
                    f"FROM {quote(table)}"
                )
                with connection.cursor() as cursor:
                    cursor.execute(sql)
                    snapshots.append({tuple(row[1:]): row[0] for row in cursor.fetchall()})
            mismatches = [
                key for key, source_id in snapshots[0].items()
                if snapshots[1].get(key) != source_id
            ]
            if mismatches:
                raise CommandError(
                    f"{table}: generated ID mapping differs for {len(mismatches)} rows; "
                    "permission relations cannot be copied safely."
                )

    def _reset_sequences(self, target, models):
        statements = target.ops.sequence_reset_sql(no_style(), list(models))
        with transaction.atomic(using=target.alias), target.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)

    def _write_report(self, path, report):
        output = Path(path)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(
            json.dumps(report, ensure_ascii=False, indent=2, default=str) + "\n",
            encoding="utf-8",
        )
